import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext(undefined);

// English translations
const enTranslations = {
  // Navigation
  "nav.home": "Home",
  "nav.courses": "Courses",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.login": "Log in",
  "nav.signup": "Sign up",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Log out",
  "nav.myCourses": "My Courses",
  "nav.assignments": "Assignments",
  "nav.messages": "Messages",
  "nav.payments": "Payments",
  "admin.nav.approver": "Add Approver",
  "admin.approver.form.title": "Add Approver",
  "admin.approver.form.subtitle": "Create an approver account. Approvers can approve or reject instructors.",
  "admin.approver.form.name": "Full Name",
  "admin.approver.form.namePlaceholder": "Full name",
  "admin.approver.form.email": "Email",
  "admin.approver.form.emailPlaceholder": "email@example.com",
  "admin.approver.form.password": "Password",
  "admin.approver.form.passwordPlaceholder": "Create a password",
  "admin.approver.form.creating": "Creating...",
  "admin.approver.form.submit": "Create Approver",
  "admin.approver.list.title": "Approvers",
  "admin.approver.list.subtitle": "Manage approved approver accounts.",
  "admin.approver.table.name": "Name",
  "admin.approver.table.email": "Email",
  "admin.approver.table.created": "Created",
  "admin.approver.table.actions": "Actions",
  "admin.approver.table.loading": "Loading...",
  "admin.approver.table.empty": "No approvers found.",
  "admin.approver.actions.view": "View approver",
  "admin.approver.actions.delete": "Delete approver",
  "admin.approver.logs.title": "Approval Activity",
  "admin.approver.logs.subtitle": "Track who approved or rejected instructors.",
  "admin.approver.logs.action": "Action",
  "admin.approver.logs.approved": "Approved",
  "admin.approver.logs.rejected": "Rejected",
  "admin.approver.logs.pending": "Pending",
  "admin.approver.logs.instructor": "Instructor",
  "admin.approver.logs.approver": "Approver",
  "admin.approver.logs.date": "Date",
  "admin.approver.logs.loading": "Loading...",
  "admin.approver.logs.empty": "No approval activity yet.",
  "admin.approver.logs.refresh": "Refresh Logs",
  "admin.approver.details.title": "Approver Details",
  "admin.approver.details.subtitle": "Account information for the approver.",
  "admin.approver.details.name": "Full Name",
  "admin.approver.details.email": "Email",
  "admin.approver.details.status": "Status",
  "admin.approver.details.created": "Created",
  "admin.approver.list.error": "Failed to load approvers",
  "admin.approver.logs.error": "Failed to load approval logs",
  "admin.approver.create.success": "Approver created successfully",
  "admin.approver.create.error": "Failed to create approver",
  "admin.approver.delete.success": "Approver deleted successfully",
  "admin.approver.delete.error": "Failed to delete approver",
  "analytics.progress.tooltip.count": "Students: {count}",
  "analytics.common.loading": "Loading...",
  "analytics.common.error": "Error: {error}",
  "analytics.enrollments.title": "Student Enrollments per Course",
  "analytics.enrollments.subtitle": "Number of students enrolled in each course by category",
  "analytics.enrollments.legend": "Number of Enrollments",
  "analytics.enrollments.tooltip.label": "Enrollments",
  "analytics.enrollments.tooltip.category": "Category",
  "analytics.enrollments.tooltip.course": "Course",
  "analytics.enrollments.empty": "No enrollment data available.",
  "analytics.enrollments.count": "{count} Enrollments",
  "analytics.categories.computerScience": "Computer Science",
  "analytics.categories.programming": "Programming",
  "analytics.categories.webDevelopment": "Web Development",
  "analytics.categories.business": "Business",
  "analytics.categories.marketing": "Marketing",
  "analytics.categories.dataScience": "Data Science",
  "analytics.categories.psychology": "Psychology",
  "analytics.categories.finance": "Finance",
  "analytics.categories.design": "Design",
  "analytics.categories.languages": "Languages",
  "analytics.categories.healthFitness": "Health & Fitness",
  "analytics.categories.mathematics": "Mathematics",
  "analytics.categories.photography": "Photography",
  "analytics.categories.music": "Music",
  "analytics.categories.other": "Other",
  "analytics.categories.machineLearning": "Machine Learning",
  "analytics.completion.title": "Course Completion Rates",
  "analytics.completion.subtitle": "Percentage of students who completed each course",
  "analytics.completion.legend": "Completion Rate (%)",
  "analytics.completion.empty": "No completion data yet.",
  "analytics.completion.error": "Failed to load completion rates",
  "analytics.completion.tooltip.label": "Completion Rate",
  "analytics.completion.tooltip.value": "{value}% ({count} students)",
  "analytics.revenue.title": "Revenue Growth",
  "analytics.revenue.subtitle": "Monthly revenue growth trend",
  "analytics.revenue.empty": "No revenue data yet.",
  "analytics.revenue.error": "Failed to load revenue growth",
  "analytics.revenue.tooltip.label": "Cumulative Revenue",
  "analytics.revenue.tooltip.value": "ETB {total} (monthly: ETB {monthly})",
  "analytics.ratings.title": "Course Ratings & Feedback",
  "analytics.ratings.subtitle": "Average ratings and number of reviews per course",
  "analytics.ratings.legend.rating": "Average Rating",
  "analytics.ratings.legend.reviews": "Number of Reviews",
  "analytics.ratings.tooltip.rating": "Average Rating",
  "analytics.ratings.tooltip.reviews": "Number of Reviews",
  "analytics.ratings.course.webDevelopment": "Web Development",
  "analytics.ratings.course.dataScience": "Data Science",
  "analytics.ratings.course.design": "Design",
  "analytics.ratings.course.marketing": "Marketing",
  "analytics.ratings.course.business": "Business",

  // Homepage
  "home.hero.title": "Learn Skills, Achieve Goals",
  "home.hero.subtitle":
    "Join thousands of students on Ethiopia's premier learning platform",
  "home.hero.cta": "Start Learning",
  "home.hero.searchPlaceholder": "What do you want to learn today?",
  "home.hero.search": "Search",
  "home.hero.popular": "Popular:",
  "home.hero.tag.web": "Web Development",
  "home.hero.tag.data": "Data Science",
  "home.hero.tag.ux": "UX Design",
  "home.hero.tag.marketing": "Marketing",
  "home.hero.tag.ai": "AI & ML",
  "home.features.title": "Why Choose Abugida",
  "home.testimonials.badge": "Student Voices",
  "home.testimonials.title": "What Our Students Say",
  "home.testimonials.description": "Hear from students who have experienced the difference our platform makes in their educational journey.",
  "home.testimonials.t1.quote": "The quality of the courses and the interactive nature of the platform has exceeded my expectations. I've been able to learn at my own pace while still feeling connected to instructors and peers.",
  "home.testimonials.t1.role": "Computer Science Student",
  "home.testimonials.t2.quote": "As someone with a busy schedule, the flexibility of Abugida has been a game-changer. The mobile responsiveness means I can learn on the go, and the real-time support has helped me overcome challenges quickly.",
  "home.testimonials.t2.role": "Business Administration",
  "home.testimonials.t3.quote": "The student services integration is what sets Abugida apart. Being able to manage my dormitory application and transcript requests in the same place I take my courses has saved me so much time and hassle.",
  "home.testimonials.t3.role": "Psychology Major",
  "home.cta.title": "Ready to Transform Your Learning Experience?",
  "home.cta.description":
    "Join thousands of students who are already benefiting from our innovative platform. Start your learning journey today!",
  "home.cta.button1": "Get Started Now",
  "home.cta.button2": "Explore Courses",

  // Popular Courses (Home)
  "popular.title": "Explore Popular Courses",
  "popular.subtitle": "Discover our most popular courses across various disciplines.",
  "popular.category.all": "All",
  "popular.category.machineLearning": "Machine Learning",
  "popular.category.web": "Web Development",
  "popular.category.business": "Business",
  "popular.category.psychology": "Psychology",
  "popular.category.finance": "Finance",
  "popular.category.design": "Design",
  "popular.category.languages": "Languages",
  "popular.sort.popularity": "Popularity",
  "popular.sort.rating": "Rating",
  "popular.sort.price": "Price",
  "popular.sort.title": "Title",
  "popular.error.title": "Error loading courses",
  "popular.error.retry": "Try Again",
  "popular.empty.title": "No courses found",
  "popular.empty.desc": "Try changing your filters or come back later",
  "popular.viewAll": "View All Courses",

  // Courses page
  "courses.title": "Explore Our Courses",
  "courses.subtitle": "Browse our extensive catalog of courses across various disciplines. Find the perfect course to advance your knowledge and skills.",
  "courses.searchPlaceholder": "Search for courses or instructors...",
  "courses.filters": "Filters",
  "courses.categories": "Categories",
  "courses.level": "Level",
  "courses.level.all": "All Levels",
  "courses.level.beginner": "Beginner",
  "courses.level.intermediate": "Intermediate",
  "courses.level.advanced": "Advanced",
  "courses.sortBy": "Sort by:",
  "courses.sort.popularity": "Popularity",
  "courses.sort.rating": "Rating",
  "courses.sort.title": "Title",
  "courses.sort.price": "Price",
  "courses.error.title": "Error loading courses",
  "courses.error.retry": "Retry",
  "courses.empty.title": "No courses found",
  "courses.empty.desc": "Try adjusting your search or filter criteria",

  // Common
  language: "Language",
  english: "English",
  amharic: "Amharic",
  darkMode: "Dark Mode",
  lightMode: "Light Mode",

  // Login
  "login.title": "Welcome back",
  "login.subtitle": "Sign in to your account to continue your learning journey",
  "login.email": "Email address",
  "login.password": "Password",
  "login.rememberMe": "Remember me",
  "login.forgot": "Forgot your password?",
  "login.signIn": "Sign in",
  "login.signingIn": "Signing in...",
  "login.noAccount": "Don't have an account?",
  "login.signUpFree": "Sign up for free",
  "login.showPassword": "Show password",
  "login.hidePassword": "Hide password",

  // Footer
  "footer.description": "A modern, interactive learning platform designed to enhance the education experience for students.",
  "footer.quickLinks": "Quick Links",
  "footer.categories": "Categories",
  "footer.contactUs": "Contact Us",
  "footer.address1": "123 Kombolcha Street",
  "footer.address2": "Kombolcha, Ethiopia",
  "footer.email": "Email: info@abugida.edu",
  "footer.phone": "Phone: +251 33 123 4567",
  "footer.rights": "All rights reserved.",
  "footer.terms": "Terms of Service",
  "footer.privacy": "Privacy Policy",
  "footer.cookies": "Cookies Policy",
  "category.development": "Development",
  "category.business": "Business",
  "category.finance": "Finance",
  "category.design": "Design",
  "category.marketing": "Marketing",
  "category.photography": "Photography",
  "category.music": "Music",

  // About page
  "about.title": "About Abugida",
  "about.subtitle": "Empowering education through technology and innovation in Ethiopia and beyond.",
  "about.missionTitle": "Our Mission",
  "about.missionP1": "At Abugida, our mission is to democratize education by providing accessible, high-quality learning experiences to students across Ethiopia.",
  "about.missionP2": "We strive to bridge educational gaps, foster continuous learning, and build a community where knowledge is shared freely and equitably.",
  "about.visionTitle": "Our Vision",
  "about.visionP1": "We envision a future where every Ethiopian has access to quality education regardless of location, background, or economic status.",
  "about.visionP2": "By harnessing technology, we aim to transform education, creating opportunities for lifelong learning and professional growth.",
  "about.valuesTitle": "Our Core Values",
  "about.valuesSubtitle": "These principles guide everything we do at Abugida, shaping our culture and approach to education.",
  "about.value.excellence.title": "Excellence",
  "about.value.excellence.desc": "We are committed to the highest standards of academic integrity and quality in all our offerings.",
  "about.value.accessibility.title": "Accessibility",
  "about.value.accessibility.desc": "Education should be accessible to all, regardless of location or economic background.",
  "about.value.community.title": "Community",
  "about.value.community.desc": "We foster a supportive community where students and instructors grow together.",
  "about.value.innovation.title": "Innovation",
  "about.value.innovation.desc": "We explore new technologies and methods to enhance learning.",
  "about.teamTitle": "Our Team",
  "about.teamSubtitle": "Meet the passionate educators and technologists behind Abugida.",
  "about.ctaTitle": "Join Our Educational Journey",
  "about.ctaDesc": "Whether you're a student eager to learn or an instructor passionate about teaching, Abugida welcomes you.",
  "about.ctaExplore": "Explore Courses",

  // Contact page
  "contact.title": "Contact Us",
  "contact.subtitle": "Have questions or feedback? We're here to help.",
  "contact.getInTouch": "Get in Touch",
  "contact.getInTouchDesc": "Questions about courses, support, or partnerships? We're ready to assist.",
  "contact.email": "Email",
  "contact.phone": "Phone",
  "contact.location": "Location",
  "contact.hours": "Hours",
  "contact.hours.weekday": "Monday - Friday: 8:30 AM - 5:00 PM",
  "contact.hours.sat": "Saturday: 9:00 AM - 1:00 PM",
  "contact.follow": "Follow Us On Social Media",
  "contact.form.title": "Send us a Message",
  "contact.form.name": "Your Name",
  "contact.form.email": "Email Address",
  "contact.form.subject": "Subject",
  "contact.form.subject.general": "General Inquiry",
  "contact.form.subject.courses": "Course Information",
  "contact.form.subject.technical": "Technical Support",
  "contact.form.subject.billing": "Billing & Payments",
  "contact.form.subject.partnership": "Partnership Opportunities",
  "contact.form.subject.other": "Other",
  "contact.form.message": "Message",
  "contact.form.placeholder.message": "Please describe how we can help you",
  "contact.form.send": "Send Message",
  "contact.form.sending": "Sending...",
  "contact.faq.title": "Frequently Asked Questions",
  "contact.faq.q1": "How do I enroll in a course?",
  "contact.faq.a1": "Create an account, browse courses, choose one, and click Enroll to complete checkout.",
  "contact.faq.q2": "Can I access courses on mobile devices?",
  "contact.faq.a2": "Yes, Abugida is responsive and works on smartphones and tablets.",
  "contact.faq.q3": "What payment methods do you accept?",
  "contact.faq.a3": "We accept Chapa payments including cards, mobile money, and bank transfers.",
  "contact.faq.q4": "How do I become an instructor?",
  "contact.faq.a4": "Register, submit required info, and after admin approval you can start teaching.",

  // Signup page
  "signup.title": "Create an account",
  "signup.subtitle": "Join us to start your learning journey",
  "signup.fullName": "Full Name",
  "signup.email": "Email Address",
  "signup.phone": "Phone Number (Optional)",
  "signup.joinAs": "Join As",
  "signup.role.student": "Student",
  "signup.role.instructor": "Instructor",
  "signup.expertise": "Expertise",
  "signup.cvLabel": "CV (PDF only, max 5MB)",
  "signup.cvHint": "Only PDF files are allowed",
  "signup.cvPlaceholder": "Click to upload your CV",
  "signup.password": "Password",
  "signup.confirmPassword": "Confirm Password",
  "signup.submit": "Create account",
  "signup.submitting": "Creating account...",
  "signup.loginCta": "Already have an account?",
  "signup.loginLink": "Log in",
  "signup.placeholder.name": "John Doe",
  "signup.placeholder.email": "your.email@example.com",
  "signup.placeholder.phone": "+1 (123) 456-7890",
  "signup.placeholder.expertise": "Your areas of expertise",

  // Student dashboard
  "student.nav.overview": "Overview",
  "student.nav.courses": "My Courses",
  "student.nav.messages": "Messages",
  "student.nav.instructors": "Instructors",
  "student.nav.settings": "Settings",
  "student.header.overview": "Dashboard Overview",
  "student.header.courses": "My Courses",
  "student.header.messages": "Messages",
  "student.header.instructors": "Instructors",
  "student.header.settings": "Platform Settings",
  "student.sidebar.namePlaceholder": "Student Name",
  "student.sidebar.emailPlaceholder": "student@example.com",
  "student.overview.welcome": "Welcome back",
  "student.overview.subtitle": "Here's what's happening with your courses today.",
  "student.overview.completed": "Completed",
  "student.overview.inProgress": "In Progress",
  "student.overview.upcoming": "Upcoming",
  "student.overview.continue": "Continue Learning",
  "student.overview.none": "No in-progress courses to display.",
  "student.overview.lastAccessed": "Last accessed",
  "student.overview.never": "Never",
  "student.overview.unknown": "Unknown",
  "student.common.complete": "complete",
  "student.courses.title": "My Learning",
  "student.courses.subtitle": "Continue your learning journey",
  "student.courses.filter.all": "All Courses",
  "student.courses.filter.inProgress": "In Progress",
  "student.courses.filter.completed": "Completed",
  "student.courses.summaryTitle": "Your Learning Summary",
  "student.courses.totalCourses": "Total Courses",
  "student.courses.completedCourses": "Completed Courses",
  "student.courses.inProgressCourses": "In Progress",
  "student.courses.viewAchievements": "View All Achievements",
  "student.courses.enrolled": "Enrolled Courses",
  "student.courses.empty.title": "No courses found",
  "student.courses.empty.all": "You haven't enrolled in any courses yet.",
  "student.courses.empty.inProgress": "You don't have any courses in progress.",
  "student.courses.empty.completed": "You haven't completed any courses yet.",
  "student.courses.percentComplete": "% complete",
  "student.courses.lessons": "lessons",
  "student.courses.lastAccessed": "Last accessed",
  "student.courses.getCertificate": "Get Certificate",
  "student.courses.continue": "Continue Learning",
  "student.messages.search": "Search messages...",
  "student.messages.filter": "Filter",
  "student.messages.recent": "Recent Conversations",
  "student.messages.unknown": "Unknown User",
  "student.messages.sentImage": "Sent an image",
  "student.messages.sentPdf": "Sent a PDF",
  "student.messages.sentFile": "Sent a file",
  "student.messages.edit.cancel": "Cancel",
  "student.messages.edit.save": "Save",
  "student.messages.inputPlaceholder": "Type your message...",
  "student.messages.selectConversation": "Select a conversation to start messaging",
  "student.messages.confirmTitle": "Confirm Deletion",
  "student.messages.confirmBody": "Are you sure you want to delete this message?",
  "student.messages.confirmCancel": "Cancel",
  "student.messages.confirmDelete": "Delete",
  "student.instructors.title": "Instructors",
  "student.instructors.empty": "No instructors found from your courses.",
  "student.instructors.coursesWith": "Courses with you:",

  // Admin dashboard
  "admin.nav.overview": "Overview",
  "admin.nav.users": "User Management",
  "admin.nav.courses": "Course Management",
  "admin.nav.analytics": "Analytics",
  "admin.nav.payments": "Payments",
  "admin.nav.approver": "Add Approver",
  "admin.nav.settings": "Settings",
  "approver.header.title": "Approver Dashboard",
  "approver.header.subtitle": "Review and approve instructor applications.",
  "approver.nav.dashboard": "Dashboard",
  "approver.sidebar.namePlaceholder": "Approver",
  "approver.sidebar.emailPlaceholder": "approver@abugida.com",
  "approver.actions.logout": "Logout",
  "approver.actions.refresh": "Refresh",
  "approver.actions.approve": "Approve",
  "approver.actions.reject": "Reject",
  "approver.actions.view": "View",
  "approver.stats.pending": "Pending Requests",
  "approver.stats.total": "Total Applicants",
  "approver.stats.quickActions": "Quick Actions",
  "approver.stats.quickActionsHint": "Keep approvals moving",
  "approver.table.title": "Pending Instructors",
  "approver.table.subtitle": "Approve or reject instructor applications.",
  "approver.search.placeholder": "Search by name or email",
  "approver.table.name": "Name",
  "approver.table.email": "Email",
  "approver.table.submitted": "Submitted",
  "approver.table.actions": "Actions",
  "approver.table.loading": "Loading...",
  "approver.table.empty": "No pending instructors.",
  "approver.table.instructor": "Instructor",
  "approver.approved.title": "Approved Instructors",
  "approver.approved.subtitle": "Previously approved instructors.",
  "approver.approved.empty": "No approved instructors yet.",
  "approver.details.title": "Instructor Details",
  "approver.details.subtitle": "Review full instructor information.",
  "approver.details.name": "Full Name",
  "approver.details.email": "Email",
  "approver.details.phone": "Phone",
  "approver.details.expertise": "Expertise",
  "approver.details.submitted": "Submitted",
  "approver.details.document": "Document",
  "approver.details.viewDocument": "View Document",
  "approver.details.noDocument": "No document provided",
  "approver.details.na": "N/A",
  "admin.header.dashboard": "Admin Dashboard",
  "admin.header.userDetails": "User Details",
  "admin.overview.welcome": "Welcome to the Admin Panel",
  "admin.overview.subtitle": "Manage users, moderate courses, view analytics, and control payments here.",
  "admin.backToUsers": "Back to User Management",
  "admin.sidebar.namePlaceholder": "Admin User",
  "admin.sidebar.emailPlaceholder": "admin@abugida.com",
  "admin.analytics.title": "Platform Analytics",
  "admin.analytics.subtitle": "Comprehensive insights into platform performance",
  "admin.analytics.statsError": "Failed to load platform stats",
  "admin.analytics.liveData": "Live data",
  "admin.analytics.totalUsers": "Total Users",
  "admin.analytics.totalStudents": "Total Students",
  "admin.analytics.totalInstructors": "Total Instructors",
  "admin.analytics.totalCourses": "Total Courses",
  "admin.analytics.totalRevenue": "Total Revenue",
  "admin.payments.title": "Payment Management",
  "admin.payments.subtitle": "Manage transactions and instructor payouts",
  "admin.payments.tabs.transactions": "Transactions",
  "admin.payments.tabs.payouts": "Instructor Payouts",
  "admin.payments.search.transactions": "Search transactions...",
  "admin.payments.search.payouts": "Search payouts...",
  "admin.payments.generateReport": "Generate Report",
  "admin.payments.reportDownloaded": "Report downloaded",
  "admin.payments.loadError": "Failed to load payment data",
  "admin.payments.table.transactionId": "Transaction ID",
  "admin.payments.table.payoutId": "Payout ID",
  "admin.payments.table.date": "Date",
  "admin.payments.table.student": "Student",
  "admin.payments.table.course": "Course",
  "admin.payments.table.amount": "Amount",
  "admin.payments.table.instructor": "Instructor",
  "admin.payments.table.courses": "Courses",
  "admin.payments.table.status": "Status",
  "admin.payments.status.approved": "Approved",
  "admin.payments.status.completed": "Completed",
  "admin.payments.status.failed": "Failed",
  "admin.payments.status.rejected": "Rejected",
  "admin.payments.status.refunded": "Refunded",
  "admin.payments.status.pending": "Pending",
  "admin.payments.status.unknown": "Unknown",
  "admin.payments.footer.showing": "Showing {showing} of {total} {type}",
  "admin.payments.footer.transactions": "transactions",
  "admin.payments.footer.payouts": "payout requests",
  "admin.payments.payoutApproved": "Payout {id} has been approved",
  "admin.payments.payoutRejected": "Payout {id} has been rejected",
  "admin.users.title": "User Management",
  "admin.users.subtitle": "Manage all users across the platform",
  "admin.users.filter.all": "All",
  "admin.users.filter.active": "Active",
  "admin.users.filter.pending": "Pending",
  "admin.users.filter.role": "Filter by role",
  "admin.users.search": "Search users...",
  "admin.users.roles.student": "Students",
  "admin.users.roles.instructor": "Instructors",
  "admin.users.roles.approver": "Approvers",
  "admin.users.table.id": "ID",
  "admin.users.table.name": "Name",
  "admin.users.table.email": "Email",
  "admin.users.table.role": "Role",
  "admin.users.table.status": "Status",
  "admin.users.table.joined": "Joined",
  "admin.users.table.actions": "Actions",
  "admin.users.actions.view": "View user",
  "admin.users.actions.block": "Block user",
  "admin.users.actions.unblock": "Unblock user",
  "admin.users.footer.showing": "Showing {showing} of {total} users",
  "admin.users.pagination.previous": "Previous",
  "admin.users.pagination.next": "Next",
  "admin.users.error.invalidResponse": "Invalid API response format",
  "admin.users.error.load": "Failed to load user data",
  "admin.users.error.block": "An error occurred while blocking the user",
  "admin.users.error.unblock": "Error unblocking user",

  // Instructor dashboard
  "instructor.tabs.overview": "Overview",
  "instructor.tabs.analytics": "Analytics",
  "instructor.tabs.myCourses": "My Courses",
  "instructor.tabs.createCourse": "Create Course",
  "instructor.loading.courses": "Loading courses...",
  "instructor.loading.stats": "Calculating course statistics...",
  "instructor.loading.dashboard": "Loading dashboard...",
  "instructor.loading.retry": "Retry",
  "instructor.toasts.startCreate": "Starting new course creation",
  "instructor.toasts.created": "Course created successfully",
  "instructor.toasts.deleted": "Course deleted",
  "instructor.toasts.loadError": "Failed to load course data",
  "instructor.toasts.deleteError": "Failed to delete course",
  "instructor.confirm.deleteCourse": "Are you sure you want to delete this course? This action cannot be undone.",
  "instructor.payments.title": "Payments",
  "instructor.certificates.title": "Certificates",
  "instructor.certificates.subtitle": "Certificate management will be displayed here.",
  "instructor.calendar.title": "Calendar",
  "instructor.calendar.subtitle": "Calendar view will be displayed here.",
  "instructor.header.dashboard": "Instructor Dashboard",
  "instructor.header.subtitle": "Track your course performance and earnings",
  "instructor.payments.subtitle": "Manage your earnings, withdrawals, and transactions",
  "instructor.payments.tabs.dashboard": "Dashboard",
  "instructor.payments.tabs.withdraw": "Withdraw Funds",
  "instructor.payments.tabs.history": "Transaction History",
  "instructor.card.grossRevenue": "Gross Revenue (100%)",
  "instructor.card.grossRevenue.help": "This is the full amount students paid.",
  "instructor.card.yourEarnings": "Your Earnings (80% share)",
  "instructor.card.yourEarnings.help": "Calculated as 80% of gross revenue.",
  "instructor.card.platformRevenue": "Platform Revenue",
  "instructor.card.totalStudents": "Total Students",
  "instructor.card.acrossCourses": "Across {count} courses",
  "instructor.card.activeCourses": "Active Courses",
  "instructor.card.completionRate": "Completion Rate",
  "instructor.card.avgRating": "Avg. Rating",
  "instructor.card.thisMonth": "this month",
  "instructor.section.coursePerformance": "Course Performance",
  "instructor.withdraw.title": "Withdraw Funds",
  "instructor.withdraw.subtitle": "Manage your withdrawals",
  "instructor.withdraw.availableBalance": "Available Balance",
  "instructor.withdraw.accountName": "Account Name",
  "instructor.withdraw.accountNumber": "Account Number",
  "instructor.withdraw.bank": "Bank",
  "instructor.withdraw.amount": "Amount (ETB)",
  "instructor.withdraw.max": "Max",
  "instructor.withdraw.initiate": "Withdraw Funds",
  "instructor.withdraw.minHint": "Minimum withdrawal amount: 100 ETB",
  "instructor.withdraw.ensureHint": "Please ensure your bank details are correct before proceeding with the withdrawal.\nFunds will be transferred to the provided account name and number.\nIf you have any issues, please contact support.",
  "instructor.withdraw.searchBanks": "Search banks...",
  "instructor.withdraw.backToForm": "Back to Withdrawal Form",
  
  // Instructor common
  "instructor.common.students": "students",
  "instructor.common.enrollments": "Enrollments",
  
  // Instructor sidebar
  "instructor.sidebar.dashboard": "Dashboard",
  "instructor.sidebar.courses": "My Courses",
  "instructor.sidebar.students": "Students",
  "instructor.sidebar.messages": "Messages",
  "instructor.sidebar.payments": "Payments",
  "instructor.sidebar.certificates": "Certificates",
  "instructor.sidebar.calendar": "Calendar",
  "instructor.sidebar.settings": "Settings",
  "instructor.sidebar.createCourse": "Create New Course",

  // Instructor course table
  "instructor.courses.title": "Your Courses",
  "instructor.courses.viewAll": "View All Courses",
  "instructor.courses.course": "Course",
  "instructor.courses.progress": "Progress",
  "instructor.courses.lastUpdated": "Last Updated",
  "instructor.courses.status": "Status",
  "instructor.courses.actions": "Actions",
  "instructor.courses.published": "Published",
  "instructor.courses.empty": "No courses found.",

  // Instructor analytics
  "instructor.analytics.title": "Instructor Analytics Dashboard",
  "instructor.analytics.range.week": "Week",
  "instructor.analytics.range.month": "Month",
  "instructor.analytics.range.quarter": "Quarter",
  "instructor.analytics.range.year": "Year",

  // Analytics: Course Earnings
  "analytics.courseEarnings.title": "Course Earnings (via {method})",
  "analytics.courseEarnings.desc": "Monthly revenue generated from course sales",
  "analytics.common.loading": "Loading…",
  "analytics.common.error": "Error:",
  "analytics.courseEarnings.empty": "No earnings data available.",

  // Analytics: Enrollments
  "analytics.enrollments.title": "Student Enrollments per Course",
  "analytics.enrollments.desc": "Total Enrollments: {total} across {count} courses",
  "analytics.enrollments.tooltip": "{name}: {value} students",
  "analytics.enrollments.empty": "No enrollment data available.",
  "analytics.enrollments.noCourses": "No courses available in this category.",

  // Analytics: Ratings
  "analytics.ratings.title": "Course Ratings & Feedback",
  "analytics.ratings.desc": "Average student ratings and recent feedback",
  "analytics.ratings.empty": "No course ratings available.",
  "analytics.ratings.latest": "Latest Feedback",
  "analytics.ratings.noFeedback": "No feedback available.",
  "analytics.ratings.reviews": "{count} reviews",

  // Analytics: time ago
  "analytics.timeAgo.year": "year",
  "analytics.timeAgo.month": "month",
  "analytics.timeAgo.week": "week",
  "analytics.timeAgo.day": "day",
  "analytics.timeAgo.hour": "hour",
  "analytics.timeAgo.minute": "minute",
  "analytics.timeAgo.justNow": "just now",
  "analytics.timeAgo.suffixAgo": "ago",

  // Instructor course creation
  "instructor.create.tabs.details": "Basic Details",
  "instructor.create.tabs.curriculum": "Curriculum",
  "instructor.create.tabs.publish": "Publish",
  "instructor.create.info.title": "Course Information",
  "instructor.create.label.title": "Course Title",
  "instructor.create.placeholder.title": "e.g. Advanced React Development",
  "instructor.create.label.description": "Course Description",
  "instructor.create.placeholder.description": "Describe your course in detail...",
  "instructor.create.help.description": "Provide a detailed description of what students will learn",
  "instructor.create.label.level": "Difficulty Level",
  "instructor.create.placeholder.level": "Select level",
  "instructor.create.level.beginner": "Beginner",
  "instructor.create.level.intermediate": "Intermediate",
  "instructor.create.level.advanced": "Advanced",
  "instructor.create.help.level": "Select the appropriate level for your course",
  "instructor.create.label.category": "Category",
  "instructor.create.placeholder.category": "Select category",
  "instructor.create.help.category": "Choose the category that best fits your course",
  "instructor.create.label.requirements": "Course Requirements",
  "instructor.create.placeholder.requirements": "List the requirements or prerequisites for your course...",
  "instructor.create.help.requirements": "Specify what students need to know or have before taking this course",
  "instructor.create.label.thumbnail": "Course Thumbnail",
  "instructor.create.upload.browse": "Upload a file",
  "instructor.create.upload.orDrag": "or drag and drop",
  "instructor.create.upload.types": "PNG, JPG, GIF up to 10MB",
  "instructor.create.upload.selected": "Selected: {name}",
  "instructor.create.help.thumbnail": "Upload a thumbnail image for your course",
  "instructor.create.label.price": "Course Price ($)",
  "instructor.create.placeholder.price": "e.g. 49.99",
  "instructor.create.help.price": "Set a price for your course",
  "instructor.create.button.continue": "Continue",

  // Instructor publish tab
  "instructor.publish.title": "Ready to Publish?",
  "instructor.publish.subtitle": "Review your course information and curriculum before publishing",
  "instructor.publish.checklist": "Publishing Checklist",
  "instructor.publish.item.meta": "Course title and description are complete",
  "instructor.publish.item.module": "At least one module with content is created",
  "instructor.publish.item.price": "Pricing information is set",
  "instructor.publish.label.switch": "Publish",
  "instructor.publish.state.published": "This course will be published",
  "instructor.publish.state.draft": "This course will remain a draft",
  "instructor.publish.button.saving": "Saving...",
  "instructor.publish.button.publish": "Publish Course",
  "instructor.publish.button.draft": "Save as Draft",
  "instructor.publish.error.missing": "Please create a course and at least one module before publishing.",

  // Analytics: Progress
  "analytics.progress.title": "Student Progress & Completion",
  "analytics.progress.desc": "Percentage of students who completed course modules",
  "analytics.progress.tooltip.pct": "{label}: {value}%",
  "analytics.progress.tooltip.count": "Number of students: {count}",

  // Analytics: Ratings
  "analytics.ratings.title": "Course Ratings & Feedback",
  "analytics.ratings.desc": "Average student ratings and recent feedback",
  "analytics.ratings.empty": "No course ratings available.",
  "analytics.ratings.latest": "Latest Feedback",
  "analytics.ratings.noFeedback": "No feedback available.",
};

// Amharic translations
const amTranslations = {
  // Navigation
  "nav.home": "መነሻ",
  "nav.courses": "ኮርሶች",
  "nav.about": "ስለኛ",
  "nav.contact": "ያግኙን",
  "nav.login": "ግባ",
  "nav.signup": "ተመዝገብ",
  "nav.dashboard": "ዳሽቦርድ",
  "nav.logout": "ውጣ",
  "nav.myCourses": "የእኔ ኮርሶች",
  "nav.assignments": "የቤት ስራዎች",
  "nav.messages": "መልእክቶች",
  "nav.payments": "ክፍያዎች",
  "admin.nav.approver": "አፕሮቨር ጨምር",
  "admin.approver.form.title": "አፕሮቨር ጨምር",
  "admin.approver.form.subtitle": "የአፕሮቨር መለያ ይፍጠሩ። አፕሮቨሮች አስተማሪዎችን ሊፍቀዱ ወይም ሊውድቁ ይችላሉ።",
  "admin.approver.form.name": "ሙሉ ስም",
  "admin.approver.form.namePlaceholder": "ሙሉ ስም",
  "admin.approver.form.email": "ኢሜል",
  "admin.approver.form.emailPlaceholder": "email@example.com",
  "admin.approver.form.password": "የይለፍ ቃል",
  "admin.approver.form.passwordPlaceholder": "የይለፍ ቃል ፍጠር",
  "admin.approver.form.creating": "በመፍጠር ላይ...",
  "admin.approver.form.submit": "አፕሮቨር ፍጠር",
  "admin.approver.list.title": "አፕሮቨሮች",
  "admin.approver.list.subtitle": "የተፈቀዱ አፕሮቨሮችን ያስተዳድሩ።",
  "admin.approver.table.name": "ስም",
  "admin.approver.table.email": "ኢሜል",
  "admin.approver.table.created": "ቀን",
  "admin.approver.table.actions": "ተግባር",
  "admin.approver.table.loading": "በመጫን ላይ...",
  "admin.approver.table.empty": "አፕሮቨሮች አልተገኙም።",
  "admin.approver.actions.view": "አፕሮቨር አሳይ",
  "admin.approver.actions.delete": "አፕሮቨር ሰርዝ",
  "admin.approver.logs.title": "የማረጋገጫ እንቅስቃሴ",
  "admin.approver.logs.subtitle": "ማን እንደፈቀደ/እንደከለ ተከታትሉ።",
  "admin.approver.logs.action": "እርምጃ",
  "admin.approver.logs.approved": "ተፈቅዷል",
  "admin.approver.logs.rejected": "ተከልክሏል",
  "admin.approver.logs.pending": "በመጠባበቅ ላይ",
  "admin.approver.logs.instructor": "አስተማሪ",
  "admin.approver.logs.approver": "አፕሮቨር",
  "admin.approver.logs.date": "ቀን",
  "admin.approver.logs.loading": "በመጫን ላይ...",
  "admin.approver.logs.empty": "የማረጋገጫ እንቅስቃሴ የለም።",
  "admin.approver.logs.refresh": "ማስታወሻዎች አድስ",
  "admin.approver.details.title": "የአፕሮቨር ዝርዝር",
  "admin.approver.details.subtitle": "ለአፕሮቨሩ የመለያ መረጃ",
  "admin.approver.details.name": "ሙሉ ስም",
  "admin.approver.details.email": "ኢሜል",
  "admin.approver.details.status": "ሁኔታ",
  "admin.approver.details.created": "ቀን",
  "admin.approver.list.error": "አፕሮቨሮችን መጫን አልተሳካም",
  "admin.approver.logs.error": "የማረጋገጫ መዝገቦች መጫን አልተሳካም",
  "admin.approver.create.success": "አፕሮቨር ተፈጥሯል",
  "admin.approver.create.error": "አፕሮቨር ማፍጠር አልተሳካም",
  "admin.approver.delete.success": "አፕሮቨር ተሰርዟል",
  "admin.approver.delete.error": "አፕሮቨር ማስወገድ አልተሳካም",

  // Homepage
  "home.hero.title": "ክህሎቶችን ይማሩ፣ ግቦችን ያሳኩ",
  "home.hero.subtitle": "በኢትዮጵያ ቀዳሚ የትምህርት መድረክ ላይ ከሺዎች ተማሪዎች ጋር ይቀላቀሉ",
  "home.hero.cta": "መማር ይጀምሩ",
  "home.hero.searchPlaceholder": "ዛሬ ምን ልትመሩ ትፈልጋላችሁ?",
  "home.hero.search": "ፈልግ",
  "home.hero.popular": "ተወዳጅ:",
  "home.hero.tag.web": "ድር ልማት",
  "home.hero.tag.data": "ዳታ ሳይንስ",
  "home.hero.tag.ux": "UX ንድፍ",
  "home.hero.tag.marketing": "ማርኬቲንግ",
  "home.hero.tag.ai": "AI እና ML",
  "home.features.title": "ፊደል ሀብን ለምን መረጡ",
  "home.testimonials.badge": "የተማሪ ድምጽ",
  "home.testimonials.title": "ተማሪዎቻችን ምን ይላሉ",
  "home.testimonials.description": "የመድረካችን ልዩነት በትምህርት ጉዞዎቻቸው ላይ እንዴት እንደሚገልጽ ከተማሪዎች ይሰሙ።",
  "home.testimonials.t1.quote": "የኮርሶች ጥራትና የመድረኩ ተግባብነት ተስፋዬን አሻሽሏል። በራሴ ፍጥነት ሳለ ማማር እችላለሁ ከአስተማሪዎችና ከቡድን ጋር የተገናኝኩ ስሜት እንዲቆይ ሲሆን።",
  "home.testimonials.t1.role": "የኮምፒዩተር ሳይንስ ተማሪ",
  "home.testimonials.t2.quote": "ስራ ክፍለ ሰዓቴ ስታስቸግረኝ ፣ የፊደል ሀብ ተለዋዋጭነት ለእኔ ለውጥ አመጣ። በሞባይል ተስማሚነት እንቅስቃሴ ላይም ልማር እችላለሁ፣ በቀጥታ ድጋፍ ፈጣን መፍትሄ አግኝቻለሁ።",
  "home.testimonials.t2.role": "የቢዝነስ አስተዳደር",
  "home.testimonials.t3.quote": "የተማሪ አገልግሎቶች ኢንቴግሬሽን ፊደል ሀብን የሚለይ ነገር ነው። የመኖሪያ ቤት መመሪያ እና የትምህርት ውጤት ጥያቄ በአንድ ቦታ እንዲኖሩ ተችሏል፣ ጊዜና ችግኝነት ብዙ አቆጥቼዋለሁ።",
  "home.testimonials.t3.role": "የስነ-ልቦና ተማሪ",
  "home.cta.title": "የመማር ልምድዎን ለመለወጥ ዝግጁ ነዎት?",
  "home.cta.description":
    "ከዚህ ቀደም ከፈጠራዊ መድረካችን ጥቅም ከሚያገኙ ሺዎች ተማሪዎች ጋር ይቀላቀሉ። የመማር ጉዞዎን ዛሬ ይጀምሩ!",
  "home.cta.button1": "አሁን ይጀምሩ",
  "home.cta.button2": "ኮርሶችን ያስሱ",

  // Popular Courses (Home)
  "popular.title": "ተወዳጅ ኮርሶችን ይፈልጉ",
  "popular.subtitle": "በተለያዩ ስርአቶች ውስጥ ያሉ ተወዳጅ ኮርሶቻችንን ያግኙ።",
  "popular.category.all": "ሁሉ",
  "popular.category.machineLearning": "ማሽን ለርነግ",
  "popular.category.web": "ድር ልማት",
  "popular.category.business": "ቢዝነስ",
  "popular.category.psychology": "ስነ-ልቦና",
  "popular.category.finance": "ፋይናንስ",
  "popular.category.design": "ዲዛይን",
  "popular.category.languages": "ቋንቋዎች",
  "popular.sort.popularity": "ተወዳጅነት",
  "popular.sort.rating": "ምድብ",
  "popular.sort.price": "ዋጋ",
  "popular.sort.title": "ርዕስ",
  "popular.error.title": "ኮርሶችን መጫን አልተሳካም",
  "popular.error.retry": "እንደገና ሞክር",
  "popular.empty.title": "ኮርሶች አልተገኙም",
  "popular.empty.desc": "ማጣሪያዎችዎን ይቀይሩ ወይም በኋላ ይመለሱ",
  "popular.viewAll": "ሁሉንም ኮርሶች ይመልከቱ",

  // Courses page
  "courses.title": "ኮርሶቻችንን ይፈልጉ",
  "courses.subtitle": "በተለያዩ መስኮች ውስጥ ያለ የኮርሶች ዝርዝር ያስሱ። እውቀትዎን እና ችሎታዎን ለማሻሻል ተስማሚ ኮርስ ያግኙ።",
  "courses.searchPlaceholder": "ኮርሶች ወይም አስተማሪዎችን ፈልጉ...",
  "courses.filters": "ማጣሪያዎች",
  "courses.categories": "ምድቦች",
  "courses.level": "ደረጃ",
  "courses.level.all": "ሁሉንም ደረጃ",
  "courses.level.beginner": "ጀማሪ",
  "courses.level.intermediate": "መካከለኛ",
  "courses.level.advanced": "የላቀ",
  "courses.sortBy": "መለያያት:",
  "courses.sort.popularity": "ተወዳጅነት",
  "courses.sort.rating": "ምድብ",
  "courses.sort.title": "ርዕስ",
  "courses.sort.price": "ዋጋ",
  "courses.error.title": "ኮርሶችን መጫን አልተሳካም",
  "courses.error.retry": "እንደገና ሞክር",
  "courses.empty.title": "ኮርሶች አልተገኙም",
  "courses.empty.desc": "የፍለጋ ወይም የማጣሪያ መስፈርቶችዎን ይለውጡ",

  // Common
  language: "ቋንቋ",
  english: "እንግሊዘኛ",
  amharic: "አማርኛ",
  darkMode: "ጨለማ ሁነታ",
  lightMode: "ብርሃን ሁነታ",

  // Login
  "login.title": "እንኳን ደህና መጣችሁ",
  "login.subtitle": "የመማር ጉዞዎን ለመቀጠል ወደ መለያዎ ይግቡ",
  "login.email": "ኢሜል አድራሻ",
  "login.password": "የይለፍ ቃል",
  "login.rememberMe": "አስታውሰኝ",
  "login.forgot": "የይለፍ ቃል ረሱኋችሁ?",
  "login.signIn": "ግባ",
  "login.signingIn": "በመግባት ላይ...",
  "login.noAccount": "መለያ የለዎትም?",
  "login.signUpFree": "ነፃ ይመዝገቡ",
  "login.showPassword": "የይለፍ ቃል አሳይ",
  "login.hidePassword": "የይለፍ ቃል ደብቅ",

  // Footer
  "footer.description": "ዘመናዊና የተግባቢ የመማሪያ መድረክ ለተማሪዎች የትምህርት ልምድን ለማሻሻል ተነድፎበታል።",
  "footer.quickLinks": "ፈጣን አገናኞች",
  "footer.categories": "ምድቦች",
  "footer.contactUs": "አግኙን",
  "footer.address1": "123 ኮምቦልቻ መንገድ",
  "footer.address2": "ኮምቦልቻ፣ ኢትዮጵያ",
  "footer.email": "ኢሜል፡ info@abugida.edu",
  "footer.phone": "ስልክ፡ +251 33 123 4567",
  "footer.rights": "መብቶች ሁሉ የተጠበቁ ናቸው።",
  "footer.terms": "የአገልግሎት ውሎች",
  "footer.privacy": "የግላዊነት ፖሊሲ",
  "footer.cookies": "የኩኪስ ፖሊሲ",
  "category.development": "ልማት",
  "category.business": "ቢዝነስ",
  "category.finance": "ፋይናንስ",
  "category.design": "ዲዛይን",
  "category.marketing": "ማርኬቲንግ",
  "category.photography": "ፎቶግራፊ",
  "category.music": "ሙዚቃ",

  // About page
  "about.title": "ስለ አቡጊዳ",
  "about.subtitle": "ትምህርትን በቴክኖሎጂና ፈጠራ በኢትዮጵያ እና በውጭ ማበረታታት",
  "about.missionTitle": "የእኛ ተልዕኮ",
  "about.missionP1": "አቡጊዳ በኢትዮጵያ ውስጥ ለተማሪዎች ተደራሽና ጥራት ያለው ትምህርት ልምድ ለመስጠት ይጥራል።",
  "about.missionP2": "የትምህርት ክፍተቶችን ማስታገስ፣ የዘወትር መማርን ማበረታታት እና እውቀት በነጻ የሚካፈልበት ማህበረሰብ መገንባት ነው አላማችን።",
  "about.visionTitle": "የእኛ ራእይ",
  "about.visionP1": "ሁሉም ኢትዮጵያዊያን ከቦታ፣ ከባህርይ ወይም ከኢኮኖሚ ሁኔታ ሳይተነሱ የጥራት ትምህርት እንዲደርስባቸው እንየያለን።",
  "about.visionP2": "በቴክኖሎጂ ጥቅም ላይ በማዋል ትምህርትን ለማሻሻል እና የዘመናዊ የመማር እድሎችን ለመፍጠር እንጥራለን።",
  "about.valuesTitle": "ዋና እሴቶቻችን",
  "about.valuesSubtitle": "እነዚህ መርሆች በአቡጊዳ የምናደርገውን ሁሉ ያመራሉ።",
  "about.value.excellence.title": "ብልጽግና",
  "about.value.excellence.desc": "በሁሉም አቅራቢያችን የአካዳሚ ጥራትን እና ኢንተግሪቲን እንጠብቃለን።",
  "about.value.accessibility.title": "ተደራሽነት",
  "about.value.accessibility.desc": "ትምህርት ለሁሉም ተደራሽ መሆን አለበት፣ ከቦታ ወይም ከኢኮኖሚ ሁኔታ ሳይተነስ።",
  "about.value.community.title": "ማህበረሰብ",
  "about.value.community.desc": "ተማሪዎችና አስተማሪዎች በአንድነት የሚያድጉበትን ድጋፍ ያለው ማህበረሰብ እንገንባለን።",
  "about.value.innovation.title": "ፈጠራ",
  "about.value.innovation.desc": "የመማር ልምድን ለማሻሻል አዳዲስ ቴክኖሎጂዎችን እና ዘዴዎችን እንመርምራለን።",
  "about.teamTitle": "ቡድናችን",
  "about.teamSubtitle": "የትምህርትን ለመቀየር የተሰጡ ባለሙያ አስተማሪዎችን እና ቴክኖሎጂ ባለሙያዎችን ይውቁ።",
  "about.ctaTitle": "በትምህርት ጉዞአችን ይቀላቀሉ",
  "about.ctaDesc": "ተማሪ ወይም አስተማሪ ቢሆኑ ፣ አቡጊዳ እንኳን ደህና መጡ ይላችሁ።",
  "about.ctaExplore": "ኮርሶችን ያስሱ",

  // Contact page
  "contact.title": "ያግኙን",
  "contact.subtitle": "ጥያቄ ወይም አስተያየት አለዎት? እዚህ ነን ለርዳታ።",
  "contact.getInTouch": "ያግኙን",
  "contact.getInTouchDesc": "ስለኮርሶች፣ ድጋፍ ወይም ግንኙነት እድሎች ጥያቄ ካለዎት እንደምን እንረዳዎት እንዘጋጃለን።",
  "contact.email": "ኢሜል",
  "contact.phone": "ስልክ",
  "contact.location": "አድራሻ",
  "contact.hours": "ሰዓታት",
  "contact.hours.weekday": "ሰኞ - ዓርብ፡ 2:30 - 11:00 ቀን",
  "contact.hours.sat": "ቅዳሜ፡ 3:00 - 7:00 ቀን",
  "contact.follow": "በማህበራዊ ሚዲያ ይከታተሉን",
  "contact.form.title": "መልእክት ይላኩልን",
  "contact.form.name": "ስምዎ",
  "contact.form.email": "ኢሜል አድራሻ",
  "contact.form.subject": "ጉዳይ",
  "contact.form.subject.general": "አጠቃላይ ጥያቄ",
  "contact.form.subject.courses": "የኮርስ መረጃ",
  "contact.form.subject.technical": "ቴክኒካዊ ድጋፍ",
  "contact.form.subject.billing": "ክፍያና ኢንቮይስ",
  "contact.form.subject.partnership": "የአብራሪ እድሎች",
  "contact.form.subject.other": "ሌላ",
  "contact.form.message": "መልእክት",
  "contact.form.placeholder.message": "እንዴት እንደምንረዳዎት ይግለጹ",
  "contact.form.send": "መልእክት ላክ",
  "contact.form.sending": "በመላክ ላይ...",
  "contact.faq.title": "ተደጋጋሚ ጥያቄዎች",
  "contact.faq.q1": "ኮርስ እንዴት እገባ?",
  "contact.faq.a1": "መለያ ይፍጠሩ፣ ኮርሶችን ያስሱ፣ ይምረጡና ኢንሮል ብለው ይጫኑ።",
  "contact.faq.q2": "በስልክ ላይ ኮርሶች እገኝ?",
  "contact.faq.a2": "አዎን፣ ፊደል ሀብ በስልክና ታብሌት ይሰራል።",
  "contact.faq.q3": "ምን ዓይነት ክፍያ ተቀባይነት አለ?",
  "contact.faq.a3": "ቻፓ በካርድ፣ ሞባይል ሞኒ እና ባንክ ትራንስፈር ይቀበላል።",
  "contact.faq.q4": "አስተማሪ እንዴት እሆናለሁ?",
  "contact.faq.a4": "ይመዝገቡ፣ መረጃዎን ያስገቡ፣ አስተዳዳሪ ከፈቀደ በኋላ ማስተማር ይጀምሩ።",

  // Signup page
  "signup.title": "መለያ ይፍጠሩ",
  "signup.subtitle": "የመማር ጉዞዎን ይጀምሩ",
  "signup.fullName": "ሙሉ ስም",
  "signup.email": "ኢሜል አድራሻ",
  "signup.phone": "የስልክ ቁጥር (አማራጭ)",
  "signup.joinAs": "እንደ... ይቀላቀሉ",
  "signup.role.student": "ተማሪ",
  "signup.role.instructor": "አስተማሪ",
  "signup.expertise": "ልምድ/ስፔሻሊቴ",
  "signup.cvLabel": "CV (PDF ብቻ፣ ከ5MB በታች)",
  "signup.cvHint": "PDF ብቻ ይፈቀዳል",
  "signup.cvPlaceholder": "CVዎን ለመጫን ጠቅ ያድርጉ",
  "signup.password": "የይለፍ ቃል",
  "signup.confirmPassword": "የይለፍ ቃል ያረጋግጡ",
  "signup.submit": "መለያ ይፍጠሩ",
  "signup.submitting": "በመፍጠር ላይ...",
  "signup.loginCta": "መለያ አለዎት?",
  "signup.loginLink": "ግባ",
  "signup.placeholder.name": "አበበ በቀለ",
  "signup.placeholder.email": "your.email@example.com",
  "signup.placeholder.phone": "+251 91 234 5678",
  "signup.placeholder.expertise": "የስፔሻሊቴዎን ያስገቡ",

  // Student dashboard
  "student.nav.overview": "አጠቃላይ",
  "student.nav.courses": "የእኔ ኮርሶች",
  "student.nav.messages": "መልእክቶች",
  "student.nav.instructors": "አስተማሪዎች",
  "student.nav.settings": "ቅንብሮች",
  "student.header.overview": "ዳሽቦርድ አጠቃላይ",
  "student.header.courses": "የእኔ ኮርሶች",
  "student.header.messages": "መልእክቶች",
  "student.header.instructors": "አስተማሪዎች",
  "student.header.settings": "የመድረክ ቅንብሮች",
  "student.sidebar.namePlaceholder": "የተማሪ ስም",
  "student.sidebar.emailPlaceholder": "student@example.com",
  "student.overview.welcome": "እንኳን ደህና መጣህ",
  "student.overview.subtitle": "ዛሬ በኮርሶችህ ላይ የሚካሄደው ይህ ነው።",
  "student.overview.completed": "ተጠናቀቀ",
  "student.overview.inProgress": "በሂደት ላይ",
  "student.overview.upcoming": "በመጪው",
  "student.overview.continue": "መማር ቀጥል",
  "student.overview.none": "በሂደት ላይ ያሉ ኮርሶች የሉም።",
  "student.overview.lastAccessed": "መጨረሻ የተመለከተው",
  "student.overview.never": "በፊት አይተህም",
  "student.overview.unknown": "ያልታወቀ",
  "student.common.complete": "ተጠናቀቀ",
  "student.courses.title": "የእኔ ትምህርት",
  "student.courses.subtitle": "የመማር ጉዞህን ቀጥል",
  "student.courses.filter.all": "ሁሉም ኮርሶች",
  "student.courses.filter.inProgress": "በሂደት ላይ",
  "student.courses.filter.completed": "ተጠናቀቀ",
  "student.courses.summaryTitle": "የመማር ማጠቃለያ",
  "student.courses.totalCourses": "አጠቃላይ ኮርሶች",
  "student.courses.completedCourses": "የተጠናቀቁ ኮርሶች",
  "student.courses.inProgressCourses": "በሂደት ላይ",
  "student.courses.viewAchievements": "ሁሉንም ስኬቶች ተመልከት",
  "student.courses.enrolled": "የተመዘገቡ ኮርሶች",
  "student.courses.empty.title": "ኮርሶች አልተገኙም",
  "student.courses.empty.all": "እስካሁን በምንም ኮርስ አልተመዘገብህም።",
  "student.courses.empty.inProgress": "በሂደት ላይ ያሉ ኮርሶች የሉህም።",
  "student.courses.empty.completed": "ያለፉ ኮርሶች የሉህም።",
  "student.courses.percentComplete": "% ተጠናቀቀ",
  "student.courses.lessons": "ትምህርቶች",
  "student.courses.lastAccessed": "መጨረሻ የተመለከተው",
  "student.courses.getCertificate": "ማረጋገጫ ያግኙ",
  "student.courses.continue": "መማር ቀጥል",
  "student.messages.search": "መልእክቶችን ይፈልጉ...",
  "student.messages.filter": "ማጣሪያ",
  "student.messages.recent": "የቅርብ ውይይቶች",
  "student.messages.unknown": "ያልታወቀ ተጠቃሚ",
  "student.messages.sentImage": "ምስል ተልኳል",
  "student.messages.sentPdf": "PDF ተልኳል",
  "student.messages.sentFile": "ፋይል ተልኳል",
  "student.messages.edit.cancel": "ይቅር",
  "student.messages.edit.save": "አስቀምጥ",
  "student.messages.inputPlaceholder": "መልእክትዎን ይጻፉ...",
  "student.messages.selectConversation": "ውይይት ለመጀመር ይምረጡ",
  "student.messages.confirmTitle": "ማጥፋትን ያረጋግጡ",
  "student.messages.confirmBody": "ይህን መልእክት ማጥፋት እንደሚፈልጉ ያረጋግጡ?",
  "student.messages.confirmCancel": "ይቅር",
  "student.messages.confirmDelete": "ያጥፉ",
  "student.instructors.title": "አስተማሪዎች",
  "student.instructors.empty": "ከኮርሶችዎ የተገኙ አስተማሪዎች የሉም።",
  "student.instructors.coursesWith": "ከእርስዎ ጋር ያሉ ኮርሶች፡",

  // Admin dashboard
  "admin.nav.overview": "አጠቃላይ",
  "admin.nav.users": "የተጠቃሚ አስተዳደር",
  "admin.nav.courses": "የኮርስ አስተዳደር",
  "admin.nav.analytics": "ትንታኔ",
  "admin.nav.payments": "ክፍያዎች",
  "admin.nav.approver": "አፕሮቨር ጨምር",
  "admin.nav.settings": "ቅንብሮች",
  "approver.header.title": "የአፕሮቨር ዳሽቦርድ",
  "approver.header.subtitle": "የአስተማሪ ማመልከቻዎችን ይመልከቱ እና ይፍቀዱ/ይከሉ።",
  "approver.nav.dashboard": "ዳሽቦርድ",
  "approver.sidebar.namePlaceholder": "አፕሮቨር",
  "approver.sidebar.emailPlaceholder": "approver@abugida.com",
  "approver.actions.logout": "ውጣ",
  "approver.actions.refresh": "አድስ",
  "approver.actions.approve": "ፍቀድ",
  "approver.actions.reject": "ውድቅ",
  "approver.actions.view": "አሳይ",
  "approver.stats.pending": "የሚጠበቁ ጥያቄዎች",
  "approver.stats.total": "አጠቃላይ ማመልከቻዎች",
  "approver.stats.quickActions": "ፈጣን ተግባሮች",
  "approver.stats.quickActionsHint": "እየፈቀዱ/እየከሉ ተግባሩን ያስቀጥሉ",
  "approver.table.title": "የሚጠበቁ አስተማሪዎች",
  "approver.table.subtitle": "የአስተማሪ ማመልከቻዎችን ይፍቀዱ ወይም ውድቅ ያድርጉ።",
  "approver.search.placeholder": "በስም ወይም በኢሜል ይፈልጉ",
  "approver.table.name": "ስም",
  "approver.table.email": "ኢሜል",
  "approver.table.submitted": "ቀን",
  "approver.table.actions": "ተግባር",
  "approver.table.loading": "በመጫን ላይ...",
  "approver.table.empty": "የሚጠበቁ አስተማሪዎች የሉም።",
  "approver.table.instructor": "አስተማሪ",
  "approver.approved.title": "የተፈቀዱ አስተማሪዎች",
  "approver.approved.subtitle": "ቀድሞ የተፈቀዱ አስተማሪዎች።",
  "approver.approved.empty": "የተፈቀዱ አስተማሪዎች የሉም።",
  "approver.details.title": "የአስተማሪ ዝርዝር",
  "approver.details.subtitle": "የአስተማሪ ሙሉ መረጃ ይመልከቱ።",
  "approver.details.name": "ሙሉ ስም",
  "approver.details.email": "ኢሜል",
  "approver.details.phone": "ስልክ",
  "approver.details.expertise": "ልምድ/ስፔሻሊቴ",
  "approver.details.submitted": "ቀን",
  "approver.details.document": "ሰነድ",
  "approver.details.viewDocument": "ሰነድ አሳይ",
  "approver.details.noDocument": "ሰነድ አልተሰጠም",
  "approver.details.na": "የለም",
  "admin.header.dashboard": "የአስተዳዳሪ ዳሽቦርድ",
  "admin.header.userDetails": "የተጠቃሚ ዝርዝር",
  "admin.overview.welcome": "እንኳን ደህና መጣችሁ ወደ አስተዳዳሪ ፓነል",
  "admin.overview.subtitle": "ተጠቃሚዎችን አስተዳድሩ፣ ኮርሶችን አስተካክሉ፣ ትንታኔ ይመልከቱ እና ክፍያዎችን ይቆጣጠሩ።",
  "admin.backToUsers": "ወደ የተጠቃሚ አስተዳደር ተመለስ",
  "admin.sidebar.namePlaceholder": "አስተዳዳሪ",
  "admin.sidebar.emailPlaceholder": "admin@abugida.com",
  "admin.analytics.title": "የመድረክ ትንታኔ",
  "admin.analytics.subtitle": "የመድረኩ አፈፃፀም ላይ ዝርዝር ትንታኔ",
  "admin.analytics.statsError": "የመድረክ ስታቲስቲክስ መጫን አልተሳካም",
  "admin.analytics.liveData": "ቀጥታ ውሂብ",
  "admin.analytics.totalUsers": "አጠቃላይ ተጠቃሚዎች",
  "admin.analytics.totalStudents": "አጠቃላይ ተማሪዎች",
  "admin.analytics.totalInstructors": "አጠቃላይ አስተማሪዎች",
  "admin.analytics.totalCourses": "አጠቃላይ ኮርሶች",
  "admin.analytics.totalRevenue": "አጠቃላይ ገቢ",
  "admin.payments.title": "የክፍያ አስተዳደር",
  "admin.payments.subtitle": "ግብይቶችን እና የአስተማሪ ክፍያዎችን ያስተዳድሩ",
  "admin.payments.tabs.transactions": "ግብይቶች",
  "admin.payments.tabs.payouts": "የአስተማሪ ክፍያዎች",
  "admin.payments.search.transactions": "ግብይቶች ይፈልጉ...",
  "admin.payments.search.payouts": "ክፍያዎች ይፈልጉ...",
  "admin.payments.generateReport": "ሪፖርት ፍጠር",
  "admin.payments.reportDownloaded": "ሪፖርት ተወርዷል",
  "admin.payments.loadError": "የክፍያ መረጃ መጫን አልተሳካም",
  "admin.payments.table.transactionId": "የግብይት መለያ",
  "admin.payments.table.payoutId": "የክፍያ መለያ",
  "admin.payments.table.date": "ቀን",
  "admin.payments.table.student": "ተማሪ",
  "admin.payments.table.course": "ኮርስ",
  "admin.payments.table.amount": "መጠን",
  "admin.payments.table.instructor": "አስተማሪ",
  "admin.payments.table.courses": "ኮርሶች",
  "admin.payments.table.status": "ሁኔታ",
  "admin.payments.status.approved": "ተፈቅዷል",
  "admin.payments.status.completed": "ተጠናቋል",
  "admin.payments.status.failed": "አልተሳካም",
  "admin.payments.status.rejected": "ተከልክሏል",
  "admin.payments.status.refunded": "ተመላሽ",
  "admin.payments.status.pending": "በመጠባበቅ ላይ",
  "admin.payments.status.unknown": "ያልታወቀ",
  "admin.payments.footer.showing": "የሚታዩ {showing} ከ {total} {type}",
  "admin.payments.footer.transactions": "ግብይቶች",
  "admin.payments.footer.payouts": "የክፍያ ጥያቄዎች",
  "admin.payments.payoutApproved": "ክፍያ {id} ተፈቅዷል",
  "admin.payments.payoutRejected": "ክፍያ {id} ተከልክሏል",
  "admin.users.title": "የተጠቃሚ አስተዳደር",
  "admin.users.subtitle": "ሁሉንም ተጠቃሚዎች ያስተዳድሩ",
  "admin.users.filter.all": "ሁሉም",
  "admin.users.filter.active": "ንቁ",
  "admin.users.filter.pending": "በመጠባበቅ ላይ",
  "admin.users.filter.role": "በሚና መስፈርት",
  "admin.users.search": "ተጠቃሚዎች ይፈልጉ...",
  "admin.users.roles.student": "ተማሪዎች",
  "admin.users.roles.instructor": "አስተማሪዎች",
  "admin.users.roles.approver": "አፕሮቨሮች",
  "admin.users.table.id": "መለያ",
  "admin.users.table.name": "ስም",
  "admin.users.table.email": "ኢሜል",
  "admin.users.table.role": "ሚና",
  "admin.users.table.status": "ሁኔታ",
  "admin.users.table.joined": "ቀን",
  "admin.users.table.actions": "ተግባር",
  "admin.users.actions.view": "ተጠቃሚ አሳይ",
  "admin.users.actions.block": "ተጠቃሚ አግድ",
  "admin.users.actions.unblock": "ተጠቃሚ ክፈት",
  "admin.users.footer.showing": "የሚታዩ {showing} ከ {total} ተጠቃሚዎች",
  "admin.users.pagination.previous": "ቀዳሚ",
  "admin.users.pagination.next": "ቀጣይ",
  "admin.users.error.invalidResponse": "የ API መልስ ቅርጸት ስህተት",
  "admin.users.error.load": "የተጠቃሚ መረጃ መጫን አልተሳካም",
  "admin.users.error.block": "ተጠቃሚን ማገድ ላይ ስህተት ተከስቷል",
  "admin.users.error.unblock": "ተጠቃሚን ማክፈት ላይ ስህተት",

  // Instructor dashboard
  "instructor.tabs.overview": "አጠቃላይ",
  "instructor.tabs.analytics": "ትንታኔ",
  "instructor.tabs.myCourses": "የእኔ ኮርሶች",
  "instructor.tabs.createCourse": "ኮርስ ፍጠር",
  "instructor.loading.courses": "ኮርሶች በመጫን ላይ...",
  "instructor.loading.stats": "የኮርስ ትንታኔ በማስላት ላይ...",
  "instructor.loading.dashboard": "ዳሽቦርድ በመጫን ላይ...",
  "instructor.loading.retry": "እንደገና ሞክር",
  "instructor.toasts.startCreate": "የኮርስ ፍጠር በመጀመር ላይ",
  "instructor.toasts.created": "ኮርስ ተሳክቶ ተፈጠረ",
  "instructor.toasts.deleted": "ኮርስ ተሰረዘ",
  "instructor.toasts.loadError": "የኮርሶች መረጃ መጫን አልተሳካም",
  "instructor.toasts.deleteError": "ኮርስ ማጥፋት አልተሳካም",
  "instructor.confirm.deleteCourse": "ይህን ኮርስ ለማጥፋት እንደምትፈልጉ ያረጋግጡ። ይህ ተግባር ሊመለስ አይችልም።",
  "instructor.payments.title": "ክፍያዎች",
  "instructor.certificates.title": "ማረጋገጫዎች",
  "instructor.certificates.subtitle": "የማረጋገጫ አስተዳደር እዚህ ይታያል።",
  "instructor.calendar.title": "ቀን መቁጠሪያ",
  "instructor.calendar.subtitle": "የቀን መቁጠሪያ እይታ እዚህ ይታያል።",
  "instructor.header.dashboard": "የአስተማሪ ዳሽቦርድ",
  "instructor.header.subtitle": "የኮርስዎን አፈጻጸምና የገቢ ክፍል ይከታተሉ",
  "instructor.payments.subtitle": "የገቢዎን ክፍል፣ ውጪ እና ትርፍ ይቀናት",
  "instructor.payments.tabs.dashboard": "ዳሽቦርድ",
  "instructor.payments.tabs.withdraw": "ገንዘብ ቀርብ",
  "instructor.payments.tabs.history": "የውሎ ታሪክ",
  "instructor.card.grossRevenue": "አጠቃላይ ገቢ (100%)",
  "instructor.card.grossRevenue.help": "የተማሪዎች ሙሉ የከፈሉት መጠን ነው።",
  "instructor.card.yourEarnings": "የእርስዎ ገቢ (80% ምርጫ)",
  "instructor.card.yourEarnings.help": "ከአጠቃላይ ገቢ 80% እንደሆነ ይቆጠራል።",
  "instructor.card.platformRevenue": "የመድረክ ገቢ",
  "instructor.card.totalStudents": "አጠቃላይ ተማሪዎች",
  "instructor.card.acrossCourses": "በ {count} ኮርሶች ውስጥ",
  "instructor.card.activeCourses": "ንቁ ኮርሶች",
  "instructor.card.completionRate": "የጨረስ መጠን",
  "instructor.card.avgRating": "መካከለኛ እይታ",
  "instructor.card.thisMonth": "በዚህ ወር",
  "instructor.section.coursePerformance": "የኮርስ አፈጻጸም",
  "instructor.withdraw.title": "ገንዘብ ቀርብ",
  "instructor.withdraw.subtitle": "የውጪዎን ሂደት ይቀናት",
  "instructor.withdraw.availableBalance": "የሚገኝ መመዝኛ",
  "instructor.withdraw.accountName": "የመለያ ስም",
  "instructor.withdraw.accountNumber": "የመለያ ቁጥር",
  "instructor.withdraw.bank": "ባንክ",
  "instructor.withdraw.amount": "መጠን (ETB)",
  "instructor.withdraw.max": "ከፍተኛ",
  "instructor.withdraw.initiate": "ገንዘብ ቀርብ",
  "instructor.withdraw.minHint": "ዝቅተኛ የውጪ መጠን: 100 ETB",
  "instructor.withdraw.ensureHint": "ከውጪ በፊት የባንክ ዝርዝሮችዎ ትክክል መሆናቸውን ያረጋግጡ።\nገንዘብ ወደ ተሰጠው የመለያ ስምና ቁጥር ይላካል።\nችግኝነት ካጋጠማችሁ ደግሞ ድጋፍን ያነጋግሩ።",
  "instructor.withdraw.searchBanks": "ባንኮችን ፈልግ...",
  "instructor.withdraw.backToForm": "ወደ ውጪ ቅርጸ ቅኝት መመለስ",
  
  // Instructor common
  "instructor.common.students": "ተማሪዎች",
  "instructor.common.enrollments": "መመዝገብ",
  
  // Instructor sidebar
  "instructor.sidebar.dashboard": "ዳሽቦርድ",
  "instructor.sidebar.courses": "ኮርሶቼ",
  "instructor.sidebar.students": "ተማሪዎች",
  "instructor.sidebar.messages": "መልዕክቶች",
  "instructor.sidebar.payments": "ክፍያዎች",
  "instructor.sidebar.certificates": "ማረጋገጫዎች",
  "instructor.sidebar.calendar": "ቀን መቁጠሪያ",
  "instructor.sidebar.settings": "ቅንብሮች",
  "instructor.sidebar.createCourse": "አዲስ ኮርስ ፍጠር",

  // Instructor course table
  "instructor.courses.title": "ኮርሶችህ",
  "instructor.courses.viewAll": "ሁሉንም ኮርሶች ይመልከቱ",
  "instructor.courses.course": "ኮርስ",
  "instructor.courses.progress": "እድገት",
  "instructor.courses.lastUpdated": "መጨረሻ የተዘመነው",
  "instructor.courses.status": "ሁኔታ",
  "instructor.courses.actions": "እርምጃዎች",
  "instructor.courses.published": "ታትሟል",
  "instructor.courses.empty": "ምንም ኮርሶች አልተገኙም።",

  // Instructor analytics
  "instructor.analytics.title": "የአስተማሪ ትንታኔ ዳሽቦርድ",
  "instructor.analytics.range.week": "ሳምንት",
  "instructor.analytics.range.month": "ወር",
  "instructor.analytics.range.quarter": "በሩብ ዓመት",
  "instructor.analytics.range.year": "ዓመት",

  // Analytics: Course Earnings
  "analytics.courseEarnings.title": "የኮርስ ገቢ (በ {method} በኩል)",
  "analytics.courseEarnings.desc": "ከኮርስ ሽያጭ የሚመነጭ ወርሃዊ ገቢ",
  "analytics.common.loading": "በመጫን ላይ…",
  "analytics.common.error": "ስህተት:",
  "analytics.courseEarnings.empty": "የገቢ መረጃ አይገኝም።",

  // Analytics: Enrollments
  "analytics.enrollments.title": "የተማሪዎች መመዝገብ በኮርስ",
  "analytics.enrollments.desc": "አጠቃላይ መመዝገብ: {total} በ {count} ኮርሶች ላይ",
  "analytics.enrollments.tooltip": "{name}: {value} መመዝገብ",
  "analytics.enrollments.empty": "የመመዝገብ መረጃ አይገኝም።",
  "analytics.enrollments.noCourses": "በዚህ ምድብ ውስጥ ኮርሶች የሉም።",

  // Analytics: Progress
  "analytics.progress.title": "የተማሪ እድገት እና ጨረስ",
  "analytics.progress.desc": "የኮርስ ሞጁሎችን ያጠናቀቁ ተማሪዎች መቶኛ",
  "analytics.progress.tooltip.pct": "{label}: {value}%",
  "analytics.progress.tooltip.count": "የተማሪዎች ብዛት: {count}",
  "analytics.common.loading": "በመጫን ላይ...",
  "analytics.common.error": "ስህተት: {error}",
  "analytics.enrollments.title": "የተማሪዎች መመዝገብ በኮርስ",
  "analytics.enrollments.subtitle": "በምድብ የተመዘገቡ ተማሪዎች ቁጥር",
  "analytics.enrollments.legend": "የመመዝገብ ብዛት",
  "analytics.enrollments.tooltip.label": "መመዝገብ",
  "analytics.enrollments.tooltip.category": "ምድብ",
  "analytics.enrollments.tooltip.course": "ኮርስ",
  "analytics.enrollments.empty": "የመመዝገብ መረጃ አይገኝም።",
  "analytics.enrollments.count": "{count} መመዝገብ",
  "analytics.categories.computerScience": "ኮምፒውተር ሳይንስ",
  "analytics.categories.programming": "ፕሮግራሚንግ",
  "analytics.categories.webDevelopment": "ዌብ ልማት",
  "analytics.categories.business": "ቢዝነስ",
  "analytics.categories.marketing": "ማርኬቲንግ",
  "analytics.categories.dataScience": "ዳታ ሳይንስ",
  "analytics.categories.psychology": "ሳይኮሎጂ",
  "analytics.categories.finance": "ፋይናንስ",
  "analytics.categories.design": "ዲዛይን",
  "analytics.categories.languages": "ቋንቋዎች",
  "analytics.categories.healthFitness": "ጤና እና አካል ብቃት",
  "analytics.categories.mathematics": "ሒሳብ",
  "analytics.categories.photography": "ፎቶግራፊ",
  "analytics.categories.music": "ሙዚቃ",
  "analytics.categories.other": "ሌሎች",
  "analytics.categories.machineLearning": "ማሽን ለርኒንግ",
  "analytics.completion.title": "የኮርስ አጠናቀቀ መጠን",
  "analytics.completion.subtitle": "እያንዳንዱን ኮርስ የአጠናቀቁ ተማሪዎች መቶኛ",
  "analytics.completion.legend": "የአጠናቀቀ መጠን (%)",
  "analytics.completion.empty": "የአጠናቀቀ መረጃ የለም።",
  "analytics.completion.error": "የአጠናቀቀ መጠን መጫን አልተሳካም",
  "analytics.completion.tooltip.label": "የአጠናቀቀ መጠን",
  "analytics.completion.tooltip.value": "{value}% ({count} ተማሪዎች)",
  "analytics.revenue.title": "የገቢ እድገት",
  "analytics.revenue.subtitle": "የወርሃዊ ገቢ እድገት አዝማሚያ",
  "analytics.revenue.empty": "የገቢ መረጃ የለም።",
  "analytics.revenue.error": "የገቢ እድገት መጫን አልተሳካም",
  "analytics.revenue.tooltip.label": "ድምር ገቢ",
  "analytics.revenue.tooltip.value": "ETB {total} (ወርሃዊ: ETB {monthly})",
  "analytics.ratings.title": "የኮርስ ደረጃ እና አስተያየት",
  "analytics.ratings.subtitle": "እያንዳንዱ ኮርስ የአማካይ ደረጃ እና የግምገማ ብዛት",
  "analytics.ratings.legend.rating": "አማካይ ደረጃ",
  "analytics.ratings.legend.reviews": "የግምገማ ብዛት",
  "analytics.ratings.tooltip.rating": "አማካይ ደረጃ",
  "analytics.ratings.tooltip.reviews": "የግምገማ ብዛት",
  "analytics.ratings.course.webDevelopment": "ዌብ ልማት",
  "analytics.ratings.course.dataScience": "ዳታ ሳይንስ",
  "analytics.ratings.course.design": "ዲዛይን",
  "analytics.ratings.course.marketing": "ማርኬቲንግ",
  "analytics.ratings.course.business": "ቢዝነስ",

  // Analytics: Ratings
  "analytics.ratings.title": "የኮርስ ምድብ እና አስተያየት",
  "analytics.ratings.desc": "የተማሪዎች መካከለኛ ምድብ እና የቅርብ ጊዜ አስተያየት",
  "analytics.ratings.empty": "የኮርስ ምድብ መረጃ አይገኝም።",
  "analytics.ratings.latest": "አዲስ አስተያየት",
  "analytics.ratings.noFeedback": "አስተያየት የለም።",
  "analytics.ratings.reviews": "{count} ግምገማዎች",

  // Analytics: time ago
  "analytics.timeAgo.year": "ዓመት",
  "analytics.timeAgo.month": "ወር",
  "analytics.timeAgo.week": "ሳምንት",
  "analytics.timeAgo.day": "ቀን",
  "analytics.timeAgo.hour": "ሰዓት",
  "analytics.timeAgo.minute": "ደቂቃ",
  "analytics.timeAgo.justNow": "አሁን አዲስ",
  "analytics.timeAgo.suffixAgo": "በፊት",

  // Instructor course creation
  "instructor.create.tabs.details": "መሰረታዊ ዝርዝሮች",
  "instructor.create.tabs.curriculum": "ኩርኒኩለም",
  "instructor.create.tabs.publish": "ማትረፍ",
  "instructor.create.info.title": "የኮርስ መረጃ",
  "instructor.create.label.title": "የኮርስ ርዕስ",
  "instructor.create.placeholder.title": "ለምሳሌ አዲስ React ኮርስ",
  "instructor.create.label.description": "የኮርስ መግለጫ",
  "instructor.create.placeholder.description": "ኮርስዎን በዝርዝር ይግለጹ...",
  "instructor.create.help.description": "ተማሪዎች የሚማሩትን በዝርዝር ይግለጹ",
  "instructor.create.label.level": "የችግኝ ደረጃ",
  "instructor.create.placeholder.level": "ደረጃ ይምረጡ",
  "instructor.create.level.beginner": "ጀማሪ",
  "instructor.create.level.intermediate": "መካከለኛ",
  "instructor.create.level.advanced": "የተሻለ",
  "instructor.create.help.level": "ለኮርስዎ ተስማሚውን ደረጃ ይምረጡ",
  "instructor.create.label.category": "ምድብ",
  "instructor.create.placeholder.category": "ምድብ ይምረጡ",
  "instructor.create.help.category": "ኮርስዎን በትክክል የሚያመለክተውን ምድብ ይምረጡ",
  "instructor.create.label.requirements": "የኮርስ መስፈርቶች",
  "instructor.create.placeholder.requirements": "የኮርሱን መስፈርቶች ይጻፉ...",
  "instructor.create.help.requirements": "ተማሪዎች ኮርሱን ከጀምሩ በፊት ሊያውቁት ያስፈልጋቸውን ያስቀምጡ",
  "instructor.create.label.thumbnail": "የኮርስ ቀለም ምስል",
  "instructor.create.upload.browse": "ፋይል ስቀል",
  "instructor.create.upload.orDrag": "ወይም ጎትተው ያድርጉ",
  "instructor.create.upload.types": "PNG, JPG, GIF እስከ 10MB",
  "instructor.create.upload.selected": "ተመርጧል: {name}",
  "instructor.create.help.thumbnail": "ለኮርስዎ ቀለም ምስል ያስገቡ",
  "instructor.create.label.price": "የኮርስ ዋጋ ($)",
  "instructor.create.placeholder.price": "ለምሳሌ 49.99",
  "instructor.create.help.price": "ለኮርሱ ዋጋ ይስፈርሙ",
  "instructor.create.button.continue": "ቀጥል",

  // Instructor publish tab
  "instructor.publish.title": "ለማትረፍ ዝግጁ ነዎት?",
  "instructor.publish.subtitle": "በማትረፍዎ በፊት የኮርስ መረጃዎን እና ኩርኒኩለሙን ይገምግሙ",
  "instructor.publish.checklist": "የማትረፍ ዝርዝር",
  "instructor.publish.item.meta": "የኮርስ ርዕስ እና መግለጫ ተሟልተዋል",
  "instructor.publish.item.module": "ከይኑን ይዘት ያለው ቢያንስ አንድ ሞጁል ተፈጥሯል",
  "instructor.publish.item.price": "የዋጋ መረጃ ተዘጋጅቷል",
  "instructor.publish.label.switch": "ማትረፍ",
  "instructor.publish.state.published": "ይህ ኮርስ ይታተማል",
  "instructor.publish.state.draft": "ይህ ኮርስ ድራፍት ይቆያል",
  "instructor.publish.button.saving": "በማስቀመጥ ላይ...",
  "instructor.publish.button.publish": "ኮርሱን አሳትም",
  "instructor.publish.button.draft": "እንደ ድራፍት አስቀምጥ",
  "instructor.publish.error.missing": "ኮርስን እና ቢያንስ አንድ ሞጁልን ከማትረፍዎ በፊት ያብጁ።",
};



export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const savedLanguage = localStorage.getItem("fidelhub-language");
    if (savedLanguage === "en" || savedLanguage === "am") return savedLanguage;
    if (savedLanguage === "ti") return "am"; // migrate legacy Tigrinya to Amharic
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("fidelhub-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (newLanguage) => {
    setLanguageState(newLanguage);
  };

  const t = (key) => {
    let translations;
    switch (language) {
      case "en":
        translations = enTranslations;
        break;
      case "am":
        translations = amTranslations;
        break;
      default:
        translations = enTranslations;
    }
    return translations[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
