import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext(undefined);

// English translations
const enTranslations = {
  // Navigation
  "nav.home": "Home",
  "nav.courses": "Courses",
  "nav.about": "About",
  "nav.contact": "Contact",
  "nav.login": "Log in",
  "nav.signup": "Sign up",
  "nav.dashboard": "Dashboard",
  "nav.logout": "Log out",
  "nav.myCourses": "My Courses",
  "nav.assignments": "Assignments",
  "nav.messages": "Messages",
  "nav.payments": "Payments",

  // Homepage
  "home.hero.title": "Learn Skills, Achieve Goals",
  "home.hero.subtitle":
    "Join thousands of students on Ethiopia's premier learning platform",
  "home.hero.cta": "Start Learning",
  "home.hero.searchPlaceholder": "What do you want to learn today?",
  "home.hero.search": "Search",
  "home.hero.popular": "Popular:",
  "home.hero.tag.web": "Web Development",
  "home.hero.tag.data": "Data Science",
  "home.hero.tag.ux": "UX Design",
  "home.hero.tag.marketing": "Marketing",
  "home.hero.tag.ai": "AI & ML",
  "home.features.title": "Why Choose Abugida",
  "home.testimonials.badge": "Student Voices",
  "home.testimonials.title": "What Our Students Say",
  "home.testimonials.description": "Hear from students who have experienced the difference our platform makes in their educational journey.",
  "home.testimonials.t1.quote": "The quality of the courses and the interactive nature of the platform has exceeded my expectations. I've been able to learn at my own pace while still feeling connected to instructors and peers.",
  "home.testimonials.t1.role": "Computer Science Student",
  "home.testimonials.t2.quote": "As someone with a busy schedule, the flexibility of Abugida has been a game-changer. The mobile responsiveness means I can learn on the go, and the real-time support has helped me overcome challenges quickly.",
  "home.testimonials.t2.role": "Business Administration",
  "home.testimonials.t3.quote": "The student services integration is what sets Abugida apart. Being able to manage my dormitory application and transcript requests in the same place I take my courses has saved me so much time and hassle.",
  "home.testimonials.t3.role": "Psychology Major",
  "home.cta.title": "Ready to Transform Your Learning Experience?",
  "home.cta.description":
    "Join thousands of students who are already benefiting from our innovative platform. Start your learning journey today!",
  "home.cta.button1": "Get Started Now",
  "home.cta.button2": "Explore Courses",

  // Popular Courses (Home)
  "popular.title": "Explore Popular Courses",
  "popular.subtitle": "Discover our most popular courses across various disciplines.",
  "popular.category.all": "All",
  "popular.category.machineLearning": "Machine Learning",
  "popular.category.web": "Web Development",
  "popular.category.business": "Business",
  "popular.category.psychology": "Psychology",
  "popular.category.finance": "Finance",
  "popular.category.design": "Design",
  "popular.category.languages": "Languages",
  "popular.sort.popularity": "Popularity",
  "popular.sort.rating": "Rating",
  "popular.sort.price": "Price",
  "popular.sort.title": "Title",
  "popular.error.title": "Error loading courses",
  "popular.error.retry": "Try Again",
  "popular.empty.title": "No courses found",
  "popular.empty.desc": "Try changing your filters or come back later",
  "popular.viewAll": "View All Courses",

  // Courses page
  "courses.title": "Explore Our Courses",
  "courses.subtitle": "Browse our extensive catalog of courses across various disciplines. Find the perfect course to advance your knowledge and skills.",
  "courses.searchPlaceholder": "Search for courses or instructors...",
  "courses.filters": "Filters",
  "courses.categories": "Categories",
  "courses.level": "Level",
  "courses.level.all": "All Levels",
  "courses.level.beginner": "Beginner",
  "courses.level.intermediate": "Intermediate",
  "courses.level.advanced": "Advanced",
  "courses.sortBy": "Sort by:",
  "courses.sort.popularity": "Popularity",
  "courses.sort.rating": "Rating",
  "courses.sort.title": "Title",
  "courses.sort.price": "Price",
  "courses.error.title": "Error loading courses",
  "courses.error.retry": "Retry",
  "courses.empty.title": "No courses found",
  "courses.empty.desc": "Try adjusting your search or filter criteria",

  // Common
  language: "Language",
  english: "English",
  amharic: "Amharic",
  darkMode: "Dark Mode",
  lightMode: "Light Mode",

  // Login
  "login.title": "Welcome back",
  "login.subtitle": "Sign in to your account to continue your learning journey",
  "login.email": "Email address",
  "login.password": "Password",
  "login.rememberMe": "Remember me",
  "login.forgot": "Forgot your password?",
  "login.signIn": "Sign in",
  "login.signingIn": "Signing in...",
  "login.noAccount": "Don't have an account?",
  "login.signUpFree": "Sign up for free",
  "login.showPassword": "Show password",
  "login.hidePassword": "Hide password",

  // Footer
  "footer.description": "A modern, interactive learning platform designed to enhance the education experience for students.",
  "footer.quickLinks": "Quick Links",
  "footer.categories": "Categories",
  "footer.contactUs": "Contact Us",
  "footer.address1": "123 Kombolcha Street",
  "footer.address2": "Kombolcha, Ethiopia",
  "footer.email": "Email: info@abugida.edu",
  "footer.phone": "Phone: +251 33 123 4567",
  "footer.rights": "All rights reserved.",
  "footer.terms": "Terms of Service",
  "footer.privacy": "Privacy Policy",
  "footer.cookies": "Cookies Policy",
  "category.development": "Development",
  "category.business": "Business",
  "category.finance": "Finance",
  "category.design": "Design",
  "category.marketing": "Marketing",
  "category.photography": "Photography",
  "category.music": "Music",

  // About page
  "about.title": "About Abugida",
  "about.subtitle": "Empowering education through technology and innovation in Ethiopia and beyond.",
  "about.missionTitle": "Our Mission",
  "about.missionP1": "At Abugida, our mission is to democratize education by providing accessible, high-quality learning experiences to students across Ethiopia.",
  "about.missionP2": "We strive to bridge educational gaps, foster continuous learning, and build a community where knowledge is shared freely and equitably.",
  "about.visionTitle": "Our Vision",
  "about.visionP1": "We envision a future where every Ethiopian has access to quality education regardless of location, background, or economic status.",
  "about.visionP2": "By harnessing technology, we aim to transform education, creating opportunities for lifelong learning and professional growth.",
  "about.valuesTitle": "Our Core Values",
  "about.valuesSubtitle": "These principles guide everything we do at Abugida, shaping our culture and approach to education.",
  "about.value.excellence.title": "Excellence",
  "about.value.excellence.desc": "We are committed to the highest standards of academic integrity and quality in all our offerings.",
  "about.value.accessibility.title": "Accessibility",
  "about.value.accessibility.desc": "Education should be accessible to all, regardless of location or economic background.",
  "about.value.community.title": "Community",
  "about.value.community.desc": "We foster a supportive community where students and instructors grow together.",
  "about.value.innovation.title": "Innovation",
  "about.value.innovation.desc": "We explore new technologies and methods to enhance learning.",
  "about.teamTitle": "Our Team",
  "about.teamSubtitle": "Meet the passionate educators and technologists behind Abugida.",
  "about.ctaTitle": "Join Our Educational Journey",
  "about.ctaDesc": "Whether you're a student eager to learn or an instructor passionate about teaching, Abugida welcomes you.",
  "about.ctaExplore": "Explore Courses",

  // Contact page
  "contact.title": "Contact Us",
  "contact.subtitle": "Have questions or feedback? We're here to help.",
  "contact.getInTouch": "Get in Touch",
  "contact.getInTouchDesc": "Questions about courses, support, or partnerships? We're ready to assist.",
  "contact.email": "Email",
  "contact.phone": "Phone",
  "contact.location": "Location",
  "contact.hours": "Hours",
  "contact.hours.weekday": "Monday - Friday: 8:30 AM - 5:00 PM",
  "contact.hours.sat": "Saturday: 9:00 AM - 1:00 PM",
  "contact.follow": "Follow Us On Social Media",
  "contact.form.title": "Send us a Message",
  "contact.form.name": "Your Name",
  "contact.form.email": "Email Address",
  "contact.form.subject": "Subject",
  "contact.form.subject.general": "General Inquiry",
  "contact.form.subject.courses": "Course Information",
  "contact.form.subject.technical": "Technical Support",
  "contact.form.subject.billing": "Billing & Payments",
  "contact.form.subject.partnership": "Partnership Opportunities",
  "contact.form.subject.other": "Other",
  "contact.form.message": "Message",
  "contact.form.placeholder.message": "Please describe how we can help you",
  "contact.form.send": "Send Message",
  "contact.form.sending": "Sending...",
  "contact.faq.title": "Frequently Asked Questions",
  "contact.faq.q1": "How do I enroll in a course?",
  "contact.faq.a1": "Create an account, browse courses, choose one, and click Enroll to complete checkout.",
  "contact.faq.q2": "Can I access courses on mobile devices?",
  "contact.faq.a2": "Yes, Abugida is responsive and works on smartphones and tablets.",
  "contact.faq.q3": "What payment methods do you accept?",
  "contact.faq.a3": "We accept Chapa payments including cards, mobile money, and bank transfers.",
  "contact.faq.q4": "How do I become an instructor?",
  "contact.faq.a4": "Register, submit required info, and after admin approval you can start teaching.",

  // Signup page
  "signup.title": "Create an account",
  "signup.subtitle": "Join us to start your learning journey",
  "signup.fullName": "Full Name",
  "signup.email": "Email Address",
  "signup.phone": "Phone Number (Optional)",
  "signup.joinAs": "Join As",
  "signup.role.student": "Student",
  "signup.role.instructor": "Instructor",
  "signup.expertise": "Expertise",
  "signup.cvLabel": "CV (PDF only, max 5MB)",
  "signup.cvHint": "Only PDF files are allowed",
  "signup.cvPlaceholder": "Click to upload your CV",
  "signup.password": "Password",
  "signup.confirmPassword": "Confirm Password",
  "signup.submit": "Create account",
  "signup.submitting": "Creating account...",
  "signup.loginCta": "Already have an account?",
  "signup.loginLink": "Log in",
  "signup.placeholder.name": "John Doe",
  "signup.placeholder.email": "your.email@example.com",
  "signup.placeholder.phone": "+1 (123) 456-7890",
  "signup.placeholder.expertise": "Your areas of expertise",

  // Student dashboard
  "student.nav.overview": "Overview",
  "student.nav.courses": "My Courses",
  "student.nav.messages": "Messages",
  "student.nav.instructors": "Instructors",
  "student.nav.settings": "Settings",
  "student.header.overview": "Dashboard Overview",
  "student.header.courses": "My Courses",
  "student.header.messages": "Messages",
  "student.header.instructors": "Instructors",
  "student.header.settings": "Platform Settings",
  "student.sidebar.namePlaceholder": "Student Name",
  "student.sidebar.emailPlaceholder": "student@example.com",
  "student.overview.welcome": "Welcome back",
  "student.overview.subtitle": "Here's what's happening with your courses today.",
  "student.overview.completed": "Completed",
  "student.overview.inProgress": "In Progress",
  "student.overview.upcoming": "Upcoming",
  "student.overview.continue": "Continue Learning",
  "student.overview.none": "No in-progress courses to display.",
  "student.overview.lastAccessed": "Last accessed",
  "student.overview.never": "Never",
  "student.overview.unknown": "Unknown",
  "student.common.complete": "complete",
  "student.courses.title": "My Learning",
  "student.courses.subtitle": "Continue your learning journey",
  "student.courses.filter.all": "All Courses",
  "student.courses.filter.inProgress": "In Progress",
  "student.courses.filter.completed": "Completed",
  "student.courses.summaryTitle": "Your Learning Summary",
  "student.courses.totalCourses": "Total Courses",
  "student.courses.completedCourses": "Completed Courses",
  "student.courses.inProgressCourses": "In Progress",
  "student.courses.viewAchievements": "View All Achievements",
  "student.courses.enrolled": "Enrolled Courses",
  "student.courses.empty.title": "No courses found",
  "student.courses.empty.all": "You haven't enrolled in any courses yet.",
  "student.courses.empty.inProgress": "You don't have any courses in progress.",
  "student.courses.empty.completed": "You haven't completed any courses yet.",
  "student.courses.percentComplete": "% complete",
  "student.courses.lessons": "lessons",
  "student.courses.lastAccessed": "Last accessed",
  "student.courses.getCertificate": "Get Certificate",
  "student.courses.continue": "Continue Learning",
  "student.messages.search": "Search messages...",
  "student.messages.filter": "Filter",
  "student.messages.recent": "Recent Conversations",
  "student.messages.unknown": "Unknown User",
  "student.messages.sentImage": "Sent an image",
  "student.messages.sentPdf": "Sent a PDF",
  "student.messages.sentFile": "Sent a file",
  "student.messages.edit.cancel": "Cancel",
  "student.messages.edit.save": "Save",
  "student.messages.inputPlaceholder": "Type your message...",
  "student.messages.selectConversation": "Select a conversation to start messaging",
  "student.messages.confirmTitle": "Confirm Deletion",
  "student.messages.confirmBody": "Are you sure you want to delete this message?",
  "student.messages.confirmCancel": "Cancel",
  "student.messages.confirmDelete": "Delete",
  "student.instructors.title": "Instructors",
  "student.instructors.empty": "No instructors found from your courses.",
  "student.instructors.coursesWith": "Courses with you:",

  // Admin dashboard
  "admin.nav.overview": "Overview",
  "admin.nav.users": "User Management",
  "admin.nav.courses": "Course Management",
  "admin.nav.analytics": "Analytics",
  "admin.nav.payments": "Payments",
  "admin.nav.settings": "Settings",
  "admin.header.dashboard": "Admin Dashboard",
  "admin.header.userDetails": "User Details",
  "admin.overview.welcome": "Welcome to the Admin Panel",
  "admin.overview.subtitle": "Manage users, moderate courses, view analytics, and control payments here.",
  "admin.backToUsers": "Back to User Management",
  "admin.sidebar.namePlaceholder": "Admin User",
  "admin.sidebar.emailPlaceholder": "admin@abugida.com",

  // Instructor dashboard
  "instructor.tabs.overview": "Overview",
  "instructor.tabs.analytics": "Analytics",
  "instructor.tabs.myCourses": "My Courses",
  "instructor.tabs.createCourse": "Create Course",
  "instructor.loading.courses": "Loading courses...",
  "instructor.loading.stats": "Calculating course statistics...",
  "instructor.loading.dashboard": "Loading dashboard...",
  "instructor.loading.retry": "Retry",
  "instructor.toasts.startCreate": "Starting new course creation",
  "instructor.toasts.created": "Course created successfully",
  "instructor.toasts.deleted": "Course deleted",
  "instructor.toasts.loadError": "Failed to load course data",
  "instructor.toasts.deleteError": "Failed to delete course",
  "instructor.confirm.deleteCourse": "Are you sure you want to delete this course? This action cannot be undone.",
  "instructor.payments.title": "Payments",
  "instructor.certificates.title": "Certificates",
  "instructor.certificates.subtitle": "Certificate management will be displayed here.",
  "instructor.calendar.title": "Calendar",
  "instructor.calendar.subtitle": "Calendar view will be displayed here.",
};

// Amharic translations
const amTranslations = {
  // Navigation
  "nav.home": "መነሻ",
  "nav.courses": "ኮርሶች",
  "nav.about": "ስለኛ",
  "nav.contact": "ያግኙን",
  "nav.login": "ግባ",
  "nav.signup": "ተመዝገብ",
  "nav.dashboard": "ዳሽቦርድ",
  "nav.logout": "ውጣ",
  "nav.myCourses": "የእኔ ኮርሶች",
  "nav.assignments": "የቤት ስራዎች",
  "nav.messages": "መልእክቶች",
  "nav.payments": "ክፍያዎች",

  // Homepage
  "home.hero.title": "ክህሎቶችን ይማሩ፣ ግቦችን ያሳኩ",
  "home.hero.subtitle": "በኢትዮጵያ ቀዳሚ የትምህርት መድረክ ላይ ከሺዎች ተማሪዎች ጋር ይቀላቀሉ",
  "home.hero.cta": "መማር ይጀምሩ",
  "home.hero.searchPlaceholder": "ዛሬ ምን ልትመሩ ትፈልጋላችሁ?",
  "home.hero.search": "ፈልግ",
  "home.hero.popular": "ተወዳጅ:",
  "home.hero.tag.web": "ድር ልማት",
  "home.hero.tag.data": "ዳታ ሳይንስ",
  "home.hero.tag.ux": "UX ንድፍ",
  "home.hero.tag.marketing": "ማርኬቲንግ",
  "home.hero.tag.ai": "AI እና ML",
  "home.features.title": "ፊደል ሀብን ለምን መረጡ",
  "home.testimonials.badge": "የተማሪ ድምጽ",
  "home.testimonials.title": "ተማሪዎቻችን ምን ይላሉ",
  "home.testimonials.description": "የመድረካችን ልዩነት በትምህርት ጉዞዎቻቸው ላይ እንዴት እንደሚገልጽ ከተማሪዎች ይሰሙ።",
  "home.testimonials.t1.quote": "የኮርሶች ጥራትና የመድረኩ ተግባብነት ተስፋዬን አሻሽሏል። በራሴ ፍጥነት ሳለ ማማር እችላለሁ ከአስተማሪዎችና ከቡድን ጋር የተገናኝኩ ስሜት እንዲቆይ ሲሆን።",
  "home.testimonials.t1.role": "የኮምፒዩተር ሳይንስ ተማሪ",
  "home.testimonials.t2.quote": "ስራ ክፍለ ሰዓቴ ስታስቸግረኝ ፣ የፊደል ሀብ ተለዋዋጭነት ለእኔ ለውጥ አመጣ። በሞባይል ተስማሚነት እንቅስቃሴ ላይም ልማር እችላለሁ፣ በቀጥታ ድጋፍ ፈጣን መፍትሄ አግኝቻለሁ።",
  "home.testimonials.t2.role": "የቢዝነስ አስተዳደር",
  "home.testimonials.t3.quote": "የተማሪ አገልግሎቶች ኢንቴግሬሽን ፊደል ሀብን የሚለይ ነገር ነው። የመኖሪያ ቤት መመሪያ እና የትምህርት ውጤት ጥያቄ በአንድ ቦታ እንዲኖሩ ተችሏል፣ ጊዜና ችግኝነት ብዙ አቆጥቼዋለሁ።",
  "home.testimonials.t3.role": "የስነ-ልቦና ተማሪ",
  "home.cta.title": "የመማር ልምድዎን ለመለወጥ ዝግጁ ነዎት?",
  "home.cta.description":
    "ከዚህ ቀደም ከፈጠራዊ መድረካችን ጥቅም ከሚያገኙ ሺዎች ተማሪዎች ጋር ይቀላቀሉ። የመማር ጉዞዎን ዛሬ ይጀምሩ!",
  "home.cta.button1": "አሁን ይጀምሩ",
  "home.cta.button2": "ኮርሶችን ያስሱ",

  // Popular Courses (Home)
  "popular.title": "ተወዳጅ ኮርሶችን ይፈልጉ",
  "popular.subtitle": "በተለያዩ ስርአቶች ውስጥ ያሉ ተወዳጅ ኮርሶቻችንን ያግኙ።",
  "popular.category.all": "ሁሉ",
  "popular.category.machineLearning": "ማሽን ለርነግ",
  "popular.category.web": "ድር ልማት",
  "popular.category.business": "ቢዝነስ",
  "popular.category.psychology": "ስነ-ልቦና",
  "popular.category.finance": "ፋይናንስ",
  "popular.category.design": "ዲዛይን",
  "popular.category.languages": "ቋንቋዎች",
  "popular.sort.popularity": "ተወዳጅነት",
  "popular.sort.rating": "ምድብ",
  "popular.sort.price": "ዋጋ",
  "popular.sort.title": "ርዕስ",
  "popular.error.title": "ኮርሶችን መጫን አልተሳካም",
  "popular.error.retry": "እንደገና ሞክር",
  "popular.empty.title": "ኮርሶች አልተገኙም",
  "popular.empty.desc": "ማጣሪያዎችዎን ይቀይሩ ወይም በኋላ ይመለሱ",
  "popular.viewAll": "ሁሉንም ኮርሶች ይመልከቱ",

  // Courses page
  "courses.title": "ኮርሶቻችንን ይፈልጉ",
  "courses.subtitle": "በተለያዩ መስኮች ውስጥ ያለ የኮርሶች ዝርዝር ያስሱ። እውቀትዎን እና ችሎታዎን ለማሻሻል ተስማሚ ኮርስ ያግኙ።",
  "courses.searchPlaceholder": "ኮርሶች ወይም አስተማሪዎችን ፈልጉ...",
  "courses.filters": "ማጣሪያዎች",
  "courses.categories": "ምድቦች",
  "courses.level": "ደረጃ",
  "courses.level.all": "ሁሉንም ደረጃ",
  "courses.level.beginner": "ጀማሪ",
  "courses.level.intermediate": "መካከለኛ",
  "courses.level.advanced": "የላቀ",
  "courses.sortBy": "መለያያት:",
  "courses.sort.popularity": "ተወዳጅነት",
  "courses.sort.rating": "ምድብ",
  "courses.sort.title": "ርዕስ",
  "courses.sort.price": "ዋጋ",
  "courses.error.title": "ኮርሶችን መጫን አልተሳካም",
  "courses.error.retry": "እንደገና ሞክር",
  "courses.empty.title": "ኮርሶች አልተገኙም",
  "courses.empty.desc": "የፍለጋ ወይም የማጣሪያ መስፈርቶችዎን ይለውጡ",

  // Common
  language: "ቋንቋ",
  english: "እንግሊዘኛ",
  amharic: "አማርኛ",
  darkMode: "ጨለማ ሁነታ",
  lightMode: "ብርሃን ሁነታ",

  // Login
  "login.title": "እንኳን ደህና መጣችሁ",
  "login.subtitle": "የመማር ጉዞዎን ለመቀጠል ወደ መለያዎ ይግቡ",
  "login.email": "ኢሜል አድራሻ",
  "login.password": "የይለፍ ቃል",
  "login.rememberMe": "አስታውሰኝ",
  "login.forgot": "የይለፍ ቃል ረሱኋችሁ?",
  "login.signIn": "ግባ",
  "login.signingIn": "በመግባት ላይ...",
  "login.noAccount": "መለያ የለዎትም?",
  "login.signUpFree": "ነፃ ይመዝገቡ",
  "login.showPassword": "የይለፍ ቃል አሳይ",
  "login.hidePassword": "የይለፍ ቃል ደብቅ",

  // Footer
  "footer.description": "ዘመናዊና የተግባቢ የመማሪያ መድረክ ለተማሪዎች የትምህርት ልምድን ለማሻሻል ተነድፎበታል።",
  "footer.quickLinks": "ፈጣን አገናኞች",
  "footer.categories": "ምድቦች",
  "footer.contactUs": "አግኙን",
  "footer.address1": "123 ኮምቦልቻ መንገድ",
  "footer.address2": "ኮምቦልቻ፣ ኢትዮጵያ",
  "footer.email": "ኢሜል፡ info@abugida.edu",
  "footer.phone": "ስልክ፡ +251 33 123 4567",
  "footer.rights": "መብቶች ሁሉ የተጠበቁ ናቸው።",
  "footer.terms": "የአገልግሎት ውሎች",
  "footer.privacy": "የግላዊነት ፖሊሲ",
  "footer.cookies": "የኩኪስ ፖሊሲ",
  "category.development": "ልማት",
  "category.business": "ቢዝነስ",
  "category.finance": "ፋይናንስ",
  "category.design": "ዲዛይን",
  "category.marketing": "ማርኬቲንግ",
  "category.photography": "ፎቶግራፊ",
  "category.music": "ሙዚቃ",

  // About page
  "about.title": "ስለ አቡጊዳ",
  "about.subtitle": "ትምህርትን በቴክኖሎጂና ፈጠራ በኢትዮጵያ እና በውጭ ማበረታታት",
  "about.missionTitle": "የእኛ ተልዕኮ",
  "about.missionP1": "አቡጊዳ በኢትዮጵያ ውስጥ ለተማሪዎች ተደራሽና ጥራት ያለው ትምህርት ልምድ ለመስጠት ይጥራል።",
  "about.missionP2": "የትምህርት ክፍተቶችን ማስታገስ፣ የዘወትር መማርን ማበረታታት እና እውቀት በነጻ የሚካፈልበት ማህበረሰብ መገንባት ነው አላማችን።",
  "about.visionTitle": "የእኛ ራእይ",
  "about.visionP1": "ሁሉም ኢትዮጵያዊያን ከቦታ፣ ከባህርይ ወይም ከኢኮኖሚ ሁኔታ ሳይተነሱ የጥራት ትምህርት እንዲደርስባቸው እንየያለን።",
  "about.visionP2": "በቴክኖሎጂ ጥቅም ላይ በማዋል ትምህርትን ለማሻሻል እና የዘመናዊ የመማር እድሎችን ለመፍጠር እንጥራለን።",
  "about.valuesTitle": "ዋና እሴቶቻችን",
  "about.valuesSubtitle": "እነዚህ መርሆች በአቡጊዳ የምናደርገውን ሁሉ ያመራሉ።",
  "about.value.excellence.title": "ብልጽግና",
  "about.value.excellence.desc": "በሁሉም አቅራቢያችን የአካዳሚ ጥራትን እና ኢንተግሪቲን እንጠብቃለን።",
  "about.value.accessibility.title": "ተደራሽነት",
  "about.value.accessibility.desc": "ትምህርት ለሁሉም ተደራሽ መሆን አለበት፣ ከቦታ ወይም ከኢኮኖሚ ሁኔታ ሳይተነስ።",
  "about.value.community.title": "ማህበረሰብ",
  "about.value.community.desc": "ተማሪዎችና አስተማሪዎች በአንድነት የሚያድጉበትን ድጋፍ ያለው ማህበረሰብ እንገንባለን።",
  "about.value.innovation.title": "ፈጠራ",
  "about.value.innovation.desc": "የመማር ልምድን ለማሻሻል አዳዲስ ቴክኖሎጂዎችን እና ዘዴዎችን እንመርምራለን።",
  "about.teamTitle": "ቡድናችን",
  "about.teamSubtitle": "የትምህርትን ለመቀየር የተሰጡ ባለሙያ አስተማሪዎችን እና ቴክኖሎጂ ባለሙያዎችን ይውቁ።",
  "about.ctaTitle": "በትምህርት ጉዞአችን ይቀላቀሉ",
  "about.ctaDesc": "ተማሪ ወይም አስተማሪ ቢሆኑ ፣ አቡጊዳ እንኳን ደህና መጡ ይላችሁ።",
  "about.ctaExplore": "ኮርሶችን ያስሱ",

  // Contact page
  "contact.title": "ያግኙን",
  "contact.subtitle": "ጥያቄ ወይም አስተያየት አለዎት? እዚህ ነን ለርዳታ።",
  "contact.getInTouch": "ያግኙን",
  "contact.getInTouchDesc": "ስለኮርሶች፣ ድጋፍ ወይም ግንኙነት እድሎች ጥያቄ ካለዎት እንደምን እንረዳዎት እንዘጋጃለን።",
  "contact.email": "ኢሜል",
  "contact.phone": "ስልክ",
  "contact.location": "አድራሻ",
  "contact.hours": "ሰዓታት",
  "contact.hours.weekday": "ሰኞ - ዓርብ፡ 2:30 - 11:00 ቀን",
  "contact.hours.sat": "ቅዳሜ፡ 3:00 - 7:00 ቀን",
  "contact.follow": "በማህበራዊ ሚዲያ ይከታተሉን",
  "contact.form.title": "መልእክት ይላኩልን",
  "contact.form.name": "ስምዎ",
  "contact.form.email": "ኢሜል አድራሻ",
  "contact.form.subject": "ጉዳይ",
  "contact.form.subject.general": "አጠቃላይ ጥያቄ",
  "contact.form.subject.courses": "የኮርስ መረጃ",
  "contact.form.subject.technical": "ቴክኒካዊ ድጋፍ",
  "contact.form.subject.billing": "ክፍያና ኢንቮይስ",
  "contact.form.subject.partnership": "የአብራሪ እድሎች",
  "contact.form.subject.other": "ሌላ",
  "contact.form.message": "መልእክት",
  "contact.form.placeholder.message": "እንዴት እንደምንረዳዎት ይግለጹ",
  "contact.form.send": "መልእክት ላክ",
  "contact.form.sending": "በመላክ ላይ...",
  "contact.faq.title": "ተደጋጋሚ ጥያቄዎች",
  "contact.faq.q1": "ኮርስ እንዴት እገባ?",
  "contact.faq.a1": "መለያ ይፍጠሩ፣ ኮርሶችን ያስሱ፣ ይምረጡና ኢንሮል ብለው ይጫኑ።",
  "contact.faq.q2": "በስልክ ላይ ኮርሶች እገኝ?",
  "contact.faq.a2": "አዎን፣ ፊደል ሀብ በስልክና ታብሌት ይሰራል።",
  "contact.faq.q3": "ምን ዓይነት ክፍያ ተቀባይነት አለ?",
  "contact.faq.a3": "ቻፓ በካርድ፣ ሞባይል ሞኒ እና ባንክ ትራንስፈር ይቀበላል።",
  "contact.faq.q4": "አስተማሪ እንዴት እሆናለሁ?",
  "contact.faq.a4": "ይመዝገቡ፣ መረጃዎን ያስገቡ፣ አስተዳዳሪ ከፈቀደ በኋላ ማስተማር ይጀምሩ።",

  // Signup page
  "signup.title": "መለያ ይፍጠሩ",
  "signup.subtitle": "የመማር ጉዞዎን ይጀምሩ",
  "signup.fullName": "ሙሉ ስም",
  "signup.email": "ኢሜል አድራሻ",
  "signup.phone": "የስልክ ቁጥር (አማራጭ)",
  "signup.joinAs": "እንደ... ይቀላቀሉ",
  "signup.role.student": "ተማሪ",
  "signup.role.instructor": "አስተማሪ",
  "signup.expertise": "ልምድ/ስፔሻሊቴ",
  "signup.cvLabel": "CV (PDF ብቻ፣ ከ5MB በታች)",
  "signup.cvHint": "PDF ብቻ ይፈቀዳል",
  "signup.cvPlaceholder": "CVዎን ለመጫን ጠቅ ያድርጉ",
  "signup.password": "የይለፍ ቃል",
  "signup.confirmPassword": "የይለፍ ቃል ያረጋግጡ",
  "signup.submit": "መለያ ይፍጠሩ",
  "signup.submitting": "በመፍጠር ላይ...",
  "signup.loginCta": "መለያ አለዎት?",
  "signup.loginLink": "ግባ",
  "signup.placeholder.name": "አበበ በቀለ",
  "signup.placeholder.email": "your.email@example.com",
  "signup.placeholder.phone": "+251 91 234 5678",
  "signup.placeholder.expertise": "የስፔሻሊቴዎን ያስገቡ",

  // Student dashboard
  "student.nav.overview": "አጠቃላይ",
  "student.nav.courses": "የእኔ ኮርሶች",
  "student.nav.messages": "መልእክቶች",
  "student.nav.instructors": "አስተማሪዎች",
  "student.nav.settings": "ቅንብሮች",
  "student.header.overview": "ዳሽቦርድ አጠቃላይ",
  "student.header.courses": "የእኔ ኮርሶች",
  "student.header.messages": "መልእክቶች",
  "student.header.instructors": "አስተማሪዎች",
  "student.header.settings": "የመድረክ ቅንብሮች",
  "student.sidebar.namePlaceholder": "የተማሪ ስም",
  "student.sidebar.emailPlaceholder": "student@example.com",
  "student.overview.welcome": "እንኳን ደህና መጣህ",
  "student.overview.subtitle": "ዛሬ በኮርሶችህ ላይ የሚካሄደው ይህ ነው።",
  "student.overview.completed": "ተጠናቀቀ",
  "student.overview.inProgress": "በሂደት ላይ",
  "student.overview.upcoming": "በመጪው",
  "student.overview.continue": "መማር ቀጥል",
  "student.overview.none": "በሂደት ላይ ያሉ ኮርሶች የሉም።",
  "student.overview.lastAccessed": "መጨረሻ የተመለከተው",
  "student.overview.never": "በፊት አይተህም",
  "student.overview.unknown": "ያልታወቀ",
  "student.common.complete": "ተጠናቀቀ",
  "student.courses.title": "የእኔ ትምህርት",
  "student.courses.subtitle": "የመማር ጉዞህን ቀጥል",
  "student.courses.filter.all": "ሁሉም ኮርሶች",
  "student.courses.filter.inProgress": "በሂደት ላይ",
  "student.courses.filter.completed": "ተጠናቀቀ",
  "student.courses.summaryTitle": "የመማር ማጠቃለያ",
  "student.courses.totalCourses": "አጠቃላይ ኮርሶች",
  "student.courses.completedCourses": "የተጠናቀቁ ኮርሶች",
  "student.courses.inProgressCourses": "በሂደት ላይ",
  "student.courses.viewAchievements": "ሁሉንም ስኬቶች ተመልከት",
  "student.courses.enrolled": "የተመዘገቡ ኮርሶች",
  "student.courses.empty.title": "ኮርሶች አልተገኙም",
  "student.courses.empty.all": "እስካሁን በምንም ኮርስ አልተመዘገብህም።",
  "student.courses.empty.inProgress": "በሂደት ላይ ያሉ ኮርሶች የሉህም።",
  "student.courses.empty.completed": "ያለፉ ኮርሶች የሉህም።",
  "student.courses.percentComplete": "% ተጠናቀቀ",
  "student.courses.lessons": "ትምህርቶች",
  "student.courses.lastAccessed": "መጨረሻ የተመለከተው",
  "student.courses.getCertificate": "ማረጋገጫ ያግኙ",
  "student.courses.continue": "መማር ቀጥል",
  "student.messages.search": "መልእክቶችን ይፈልጉ...",
  "student.messages.filter": "ማጣሪያ",
  "student.messages.recent": "የቅርብ ውይይቶች",
  "student.messages.unknown": "ያልታወቀ ተጠቃሚ",
  "student.messages.sentImage": "ምስል ተልኳል",
  "student.messages.sentPdf": "PDF ተልኳል",
  "student.messages.sentFile": "ፋይል ተልኳል",
  "student.messages.edit.cancel": "ይቅር",
  "student.messages.edit.save": "አስቀምጥ",
  "student.messages.inputPlaceholder": "መልእክትዎን ይጻፉ...",
  "student.messages.selectConversation": "ውይይት ለመጀመር ይምረጡ",
  "student.messages.confirmTitle": "ማጥፋትን ያረጋግጡ",
  "student.messages.confirmBody": "ይህን መልእክት ማጥፋት እንደሚፈልጉ ያረጋግጡ?",
  "student.messages.confirmCancel": "ይቅር",
  "student.messages.confirmDelete": "ያጥፉ",
  "student.instructors.title": "አስተማሪዎች",
  "student.instructors.empty": "ከኮርሶችዎ የተገኙ አስተማሪዎች የሉም።",
  "student.instructors.coursesWith": "ከእርስዎ ጋር ያሉ ኮርሶች፡",

  // Admin dashboard
  "admin.nav.overview": "አጠቃላይ",
  "admin.nav.users": "የተጠቃሚ አስተዳደር",
  "admin.nav.courses": "የኮርስ አስተዳደር",
  "admin.nav.analytics": "ትንታኔ",
  "admin.nav.payments": "ክፍያዎች",
  "admin.nav.settings": "ቅንብሮች",
  "admin.header.dashboard": "የአስተዳዳሪ ዳሽቦርድ",
  "admin.header.userDetails": "የተጠቃሚ ዝርዝር",
  "admin.overview.welcome": "እንኳን ደህና መጣችሁ ወደ አስተዳዳሪ ፓነል",
  "admin.overview.subtitle": "ተጠቃሚዎችን አስተዳድሩ፣ ኮርሶችን አስተካክሉ፣ ትንታኔ ይመልከቱ እና ክፍያዎችን ይቆጣጠሩ።",
  "admin.backToUsers": "ወደ የተጠቃሚ አስተዳደር ተመለስ",
  "admin.sidebar.namePlaceholder": "አስተዳዳሪ",
  "admin.sidebar.emailPlaceholder": "admin@abugida.com",

  // Instructor dashboard
  "instructor.tabs.overview": "አጠቃላይ",
  "instructor.tabs.analytics": "ትንታኔ",
  "instructor.tabs.myCourses": "የእኔ ኮርሶች",
  "instructor.tabs.createCourse": "ኮርስ ፍጠር",
  "instructor.loading.courses": "ኮርሶች በመጫን ላይ...",
  "instructor.loading.stats": "የኮርስ ትንታኔ በማስላት ላይ...",
  "instructor.loading.dashboard": "ዳሽቦርድ በመጫን ላይ...",
  "instructor.loading.retry": "እንደገና ሞክር",
  "instructor.toasts.startCreate": "የኮርስ ፍጠር በመጀመር ላይ",
  "instructor.toasts.created": "ኮርስ ተሳክቶ ተፈጠረ",
  "instructor.toasts.deleted": "ኮርስ ተሰረዘ",
  "instructor.toasts.loadError": "የኮርሶች መረጃ መጫን አልተሳካም",
  "instructor.toasts.deleteError": "ኮርስ ማጥፋት አልተሳካም",
  "instructor.confirm.deleteCourse": "ይህን ኮርስ ለማጥፋት እንደምትፈልጉ ያረጋግጡ። ይህ ተግባር ሊመለስ አይችልም።",
  "instructor.payments.title": "ክፍያዎች",
  "instructor.certificates.title": "ማረጋገጫዎች",
  "instructor.certificates.subtitle": "የማረጋገጫ አስተዳደር እዚህ ይታያል።",
  "instructor.calendar.title": "ቀን መቁጠሪያ",
  "instructor.calendar.subtitle": "የቀን መቁጠሪያ እይታ እዚህ ይታያል።",
};



export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const savedLanguage = localStorage.getItem("fidelhub-language");
    if (savedLanguage === "en" || savedLanguage === "am") return savedLanguage;
    if (savedLanguage === "ti") return "am"; // migrate legacy Tigrinya to Amharic
    return "en";
  });

  useEffect(() => {
    localStorage.setItem("fidelhub-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (newLanguage) => {
    setLanguageState(newLanguage);
  };

  const t = (key) => {
    let translations;
    switch (language) {
      case "en":
        translations = enTranslations;
        break;
      case "am":
        translations = amTranslations;
        break;
      default:
        translations = enTranslations;
    }
    return translations[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
